<input id="requestUriRegulated" type="hidden"  value="<?php echo $this->requestUriRegulated; ?>"></input>
<input id="langCode" type="hidden"  value="<?php echo $this->langCode; ?>"></input>
<input id="pk" type="hidden"  value="<?php echo $this->publicKey; ?>"></input>
<input id="ln" type="hidden"  value="tr"></input>
<input id="controller" type="hidden"  value="<?php echo $this->layout()->controller; ?>"></input>
<input id="module" type="hidden"  value="<?php echo $this->layout()->module; ?>"></input>

admin view katmanına action ve modül değşkenleri eklendi

<body class="skin-blue sidebar-mini">
    <div class="wrapper">

        <header class="main-header">
            <!-- Logo -->
            <a href="index.phtml" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b> <?php echo $this->translate('4') ?> </b></span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b> <?php echo $this->translate('4') ?> </b> <?php echo $this->translate('6') ?> </span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- Messages: style can be found in dropdown.less-->
                        <li class="dropdown messages-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-envelope-o"></i>
                                <span class="label label-success">0</span>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="header">0 <?php echo $this->translate('22') ?></li>
                                <li>
                                    <!-- inner menu: contains the actual data -->
                                    <ul class="menu">
                                        
                                    </ul>
                                </li>
                                <li class="footer"><a href="#"><?php echo $this->translate('23') ?></a></li>
                            </ul>
                        </li>
                        <!-- Notifications: style can be found in dropdown.less -->
                        <li class="dropdown notifications-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-bell-o"></i>
                                <span class="label label-warning">0</span>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="header">0 <?php echo $this->translate('20') ?></li>
                                <li>
                                    <!-- inner menu: contains the actual data -->
                                    <ul class="menu">
                                        
                                    </ul>
                                </li>
                                <li class="footer"><a href="#"><?php echo $this->translate('21') ?></a></li>
                            </ul>
                        </li>
                        <!-- Tasks: style can be found in dropdown.less -->
                        <li class="dropdown tasks-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-flag-o"></i>
                                <span class="label label-danger">0</span>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="header">0 <?php echo $this->translate('24') ?></li>
                                <li>
                                    <!-- inner menu: contains the actual data -->
                                    <ul class="menu">
                                        
                                    </ul>
                                </li>
                                <li class="footer">
                                    <a href="#"><?php echo $this->translate('25') ?></a>
                                </li>
                            </ul>
                        </li>
                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                              <!--<img src="dist/img/user2-160x160.jpg" class="user-image" alt="User Image"/>-->                    
                                <img src="<?php echo $this->basePath('dist/img/manager-xxl.png') ?>" class="user-image" alt="User Image"/> 
                                <span class="hidden-xs"><?php /* echo $_SESSION['userName'] */ ?></span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header">
                                  <!--<img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image" />-->
                                    <img src="<?php echo $this->basePath('dist/img/manager-xxl.png') ?>" class="user-image" alt="User Image"/> 
                                    <p>
                                        <?php /* echo $_SESSION['userName'] */ ?> - <?php /* echo $_SESSION['department'] */ ?>
                                        <small><!--Member since Nov. 2012--></small>
                                    </p>
                                </li>
                                <!-- Menu Body -->
                                <li class="user-body">
                                    <div class="col-xs-4 text-center">
                                        <a href="#"><?php echo $this->translate('26') ?></a>
                                    </div>
                                    <div class="col-xs-4 text-center">
                                        <a href="#"><?php echo $this->translate('27') ?></a>
                                    </div>
                                    <div class="col-xs-4 text-center">
                                        <a href="#"><?php echo $this->translate('28') ?></a>
                                    </div>
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">   
                                        <a href="#" class="btn btn-default btn-flat"><?php echo $this->translate('29') ?></a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="<?php echo $this->url('login', array('action' => 'logout')); ?> " class="btn btn-default btn-flat"><?php echo $this->translate('31') ?></a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                        <!-- Control Sidebar Toggle Button -->
                        <li>
                            <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->

        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <div class="user-panel">
                    <div class="pull-left image">
                      <!--<img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image" />-->
                        <img src="<?php echo $this->basePath('dist/img/manager-xxl.png') ?>" class="user-image" alt="User Image"/> 

                    </div>
                    <div class="pull-left info">
                        <p><?php /* echo $_SESSION['userName']; */ ?></p>

                        <a href="#"><i class="fa fa-circle text-success"></i> <?php echo $this->translate('7') ?></a>
                    </div>
                </div>
                <!-- search form -->
                <form action="#" method="get" class="sidebar-form">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="Ara..."/>
                        <span class="input-group-btn">
                            <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
                        </span>
                    </div>
                </form>
                <!-- /.search form -->
                <!-- sidebar menu: : style can be found in sidebar.less -->

                <ul class="sidebar-menu" id="leftside-menu">
                    <li class="header"><?php echo $this->translate('8') ?></li>
                    <li class="active treeview"></li>                        
                </ul>

            </section>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    <?php echo $this->translate('2') ?> - 
                    
                    <?php echo $this->translate('543') ?>
                    <small></small>
                </h1>
                <ol class="breadcrumb">
                    <li><a href="https://www.bahram.sanalfabrika.com/tr/ostim/sanalfabrika/supervisor"><i class="fa fa-dashboard"></i> <?php echo $this->translate('Home') ?> </a></li>
                    <!--<li class="active">Firma İşlemleri</li>-->
                </ol>
            </section>
            <!-- Main content -->
            <section class="content">
                <!-- Small boxes (Stat box) -->
                <!--first collapsible panel row -->
                <div class="row">
                    <!--first collapsible panel width, single column-->
                    <div class="col-md-12">
                        <!--arrange first panel color to blue by assigning primary class-->
                        <div class="box box-primary">
                            <!--First panel Header-->
                            <div class="box-header with-border">                                                    
                                <h3 class="box-title"> Role Tree </h3>                                                    
                                <!--Panel 1 collapse button-->
                                <div class="box-tools pull-right">
                                    <button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse"><i class="fa fa-minus"></i></button>
                                </div><!--/. button div-->
                            </div><!--/. panel 1 header div-->
                            <!--Panel 1 contents-->
                            <div class="box-body">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <form id='roleForm' method="get" class="form-horizontal">  

                                            <!-- Search roles box -->
                                            <!--                                            <div class="form-group">
                                                                                            <label class="col-sm-2 control-label"><?php echo $this->translate('544') ?></label>
                                                                                            <div class="col-sm-10">
                                                                                                <div class="input-group margin">
                                                                                                    <div class="input-group-addon">
                                                                                                        <i class="fa fa-hand-o-right"></i>
                                                                                                    </div>
                                                                                                    <input class="form-control validate[not-required,custom[onlyLetterNumber]]" type="text" name="searchRole" id="searchRole">                                                        
                                                                                                    <span class="input-group-btn">
                                                                                                        <button class="btn btn-info btn-flat" type="button" onclick="searchForRoles()"><?php echo $this->translate('Go') ?></button>
                                                                                                    </span>
                                                                                                </div> /input-group 
                                                                                            </div>
                                                                                        </div>//form group-->

                                            <div class="hr-line-dashed"></div>

                                            <!--Easyui tree  div start-->
                                            <div id="roleFormBlock" class="box box-primary">                                             
                                                <div class="form-group">
                                                    <label class="col-sm-2 control-label"><?php echo $this->translate('545') ?></label>
                                                    <div class="col-sm-10">
                                                        <div class="input-group">
                                                            <div class="input-group-addon">
                                                                <i class="fa fa-code-fork"></i>
                                                            </div>
                                                            <div class="inner">
                                                                <div id="loading-image">
                                                                <ul id="tt_tree_roles" class="easyui-tree" ></ul> 
                                                                </div>
                                                            </div>                                                       
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>  
                                            <div class="form-group">
                                                <label class="col-sm-2 control-label"><?php echo $this->translate('546') ?></label>
                                                <div class="col-sm-10">
                                                    <div class="input-group">
                                                        <div class="input-group-addon">
                                                            <i class="fa fa-hand-o-right"></i>
                                                        </div>
                                                        <input class="form-control validate[required,custom[onlyLetterNumber]]" type="text" name="roleName" id="roleName" />
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="hr-line-dashed"></div>
                                            <div class="form-group">
                                                <label class="col-sm-2 control-label"><?php echo $this->translate('201') ?></label>
                                                <div class="col-sm-10">
                                                    <div class="input-group">
                                                        <div class="input-group-addon">
                                                            <i class="fa fa-hand-o-right"></i>
                                                        </div>
                                                        <input class="form-control validate[not-required,custom[onlyLetterNumber]]" type="text" name="roleDescription" id="roleDescription" />
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="hr-line-dashed"></div>
                                            <div class="form-group">
                                                <div class="col-sm-10 col-sm-offset-2">
                                                    <!--<button id="activationRole" class="btn btn-white" type="submit"> Change Activation </button>
                                                    <button id="deleteRole" class="btn btn-white" type="submit"> Sil </button>-->
                                                    <button id="submitRole" class="btn btn-primary" type="submit"><i class="fa fa-save"></i> Kaydet </button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>  
                            </div><!-- /.box-body -->
                        </div><!--/. primary box div-->
                    </div><!--/. first panel single column div -->
                </div><!-- / first panel row-->


                <!--second collapsible panel row -->
                <div class="row">
                    <!--second collapsible panel width, single column-->
                    <div class="col-md-12">
                        <!--arrange second panel color to blue by assigning primary class-->
                        <div class="box box-success">
                            <!--second panel Header-->
                            <div class="box-header with-border">                                                    
                                <h3 class="box-title"> Resources Tree </h3>                                                    
                                <!--Panel 2 collapse button-->
                                <div class="box-tools pull-right">
                                    <button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse"><i class="fa fa-minus"></i></button>
                                </div><!--/. button div-->
                            </div><!--/. panel 2 header div-->
                            <!--Panel 2 contents-->
                            <div class="box-body">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <form id='resourceForm' method="get" class="form-horizontal">
                                            <!--Easyui tree table div start-->
                                            <div class="form-group">
                                                <label class="col-sm-2 control-label"><?php echo $this->translate('547') ?></label>
                                                <div class="col-sm-10">
                                                    <div class="input-group">
                                                        <div class="input-group-addon">
                                                            <i class="fa fa-code-fork"></i>
                                                        </div>
                                                        <ul id="tt_tree_resources" class="easyui-tree" ></ul>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-sm-2 control-label"><?php echo $this->translate('548') ?></label>
                                                <div class="col-sm-10">
                                                    <div class="input-group">
                                                        <div class="input-group-addon">
                                                            <i class="fa fa-hand-o-right"></i>
                                                        </div>
                                                        <input class="form-control validate[required,custom[onlyLetterNumber]]" type="text" name="resourceName" id="resourceName" />
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <label class="col-sm-2 control-label"><?php echo $this->translate('549') ?></label>
                                                <div class="col-sm-10">
                                                    <div class="input-group">
                                                        <div class="input-group-addon">
                                                            <i class="fa fa-hand-o-right"></i>
                                                        </div>
                                                        <input class="form-control validate[required,custom[url]]" type="url" name="resourceURL" id="resourceURL" />
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-sm-2 control-label"><?php echo $this->translate('550') ?></label>
                                                <div class="col-sm-10">
                                                    <div class="input-group">
                                                        <div class="input-group-addon">
                                                            <i class="fa fa-hand-o-right"></i>
                                                        </div>
                                                        <input class="form-control validate[required,custom[onlyLetterNumber]]" type="text" name="resourceIP" id="resourceIP" />                                                
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-sm-2 control-label"><?php echo $this->translate('551') ?></label>
                                                <div class="col-sm-10">
                                                    <div class="input-group">
                                                        <div class="input-group-addon">
                                                            <i class="fa fa-hand-o-right"></i>
                                                        </div>                                                    
                                                        <input class="form-control validate[required,custom[onlyLetterNumber]]" type="text" name="resourceDesc" id="resourceDesc" />
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="hr-line-dashed"></div>

                                            <div class="form-group">
                                                <div class="col-sm-10 col-sm-offset-2">
                                                    <button class="btn btn-white" type="submit"> <?php echo $this->translate('132') ?> </button>
                                                    <button class="btn btn-primary" type="submit"> <?php echo $this->translate('131') ?> </button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>  
                            </div><!-- /.box-body -->
                        </div><!--/. primary box div-->
                    </div><!--/. second panel single column div -->
                </div><!-- / second panel row-->



                <!--third collapsible panel row -->
                <div class="row">
                    <!--third collapsible panel width, single column-->
                    <div class="col-md-12">
                        <!--arrange third panel color to blue by assigning primary class-->
                        <div class="box box-success">
                            <!--third panel Header-->
                            <div class="box-header with-border">                                                    
                                <h3 class="box-title"> Privileges Tree </h3>                                                    
                                <!--Panel 2 collapse button-->
                                <div class="box-tools pull-right">
                                    <button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse"><i class="fa fa-minus"></i></button>
                                </div><!--/. button div-->
                            </div><!--/. panel 3 header div-->
                            <!--Panel 3 contents-->
                            <div class="box-body">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <form id="privelegeForm" method="get" class="form-horizontal">
                                            <!--Easyui tree table div start-->
                                            <div class="form-group">
                                                <label class="col-sm-2 control-label"><?php echo $this->translate('552') ?></label>
                                                <div class="col-sm-10">
                                                    <div class="input-group">
                                                        <div class="input-group-addon">
                                                            <i class="fa fa-code-fork"></i>
                                                        </div>
                                                        <ul id="tt_tree_privilege" class="easyui-tree" ></ul>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-sm-2 control-label"><?php echo $this->translate('553') ?></label>
                                                <div class="col-sm-10">
                                                    <div class="input-group">
                                                        <div class="input-group-addon">
                                                            <i class="fa fa-hand-o-right"></i>
                                                        </div>
                                                        <input class="form-control validate[required,custom[onlyLetterNumber]]" type="text" name="privilegeName" id="privelegeName" />
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-sm-2 control-label"><?php echo $this->translate('554') ?></label>
                                                <div class="col-sm-10">
                                                    <div class="input-group">
                                                        <div class="input-group-addon">
                                                            <i class="fa fa-hand-o-right"></i>
                                                        </div>
                                                        <input class="form-control validate[required,custom[onlyLetterNumber]]" type="url" name="privilegeurl" id="privilegeurl" />
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-sm-2 control-label"><?php echo $this->translate('555') ?></label>
                                                <div class="col-sm-10">
                                                    <div class="input-group">
                                                        <div class="input-group-addon">
                                                            <i class="fa fa-hand-o-right"></i>
                                                        </div>
                                                        <input class="form-control validate[required,custom[onlyLetterNumber]]" type="text" name="privilegDesc" id="privilegDesc" />
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="hr-line-dashed"></div>

                                            <div class="form-group">
                                                <div class="col-sm-10 col-sm-offset-2">                                                    
                                                    <button class="btn btn-white" type="submit"> <?php echo $this->translate('132') ?> </button>
                                                    <button class="btn btn-primary" type="submit"> <?php echo $this->translate('131') ?> </button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>  
                            </div><!-- /.box-body -->
                        </div><!--/. primary box div-->
                    </div><!--/. third panel single column div -->
                </div><!-- / third panel row-->

            </section><!-- /.content -->
        </div><!-- /.content-wrapper -->
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b><?php echo $this->translate('73') ?></b> 1.0
            </div>
            <strong><?php echo $this->translate('72') ?> &copy; 2016 <a href="" onclick="event.preventDefault();"><?php echo $this->translate('5') ?></a></strong> <?php echo $this->translate('71') ?>
        </footer>

        <!-- Control Sidebar -->      
        <aside class="control-sidebar control-sidebar-dark">                
            <!-- Create the tabs -->
            <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
                <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>

                <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
            </ul>
            <!-- Tab panes -->
            <div class="tab-content">
                <!-- Home tab content -->
                <div class="tab-pane" id="control-sidebar-home-tab">
                    <h3 class="control-sidebar-heading"><?php echo $this->translate('58') ?></h3>
                    <ul class='control-sidebar-menu'>
                        <li>
                            <a href='javascript::;'>
                                <i class="menu-icon-zeyn fa fa-file-code-o bg-green"></i>
                                <div class="menu-info">
                                    <h4 class="control-sidebar-subheading"><?php echo $this->translate('533') ?></h4>
                                    <p><!--Will be 23 on April 24th--></p>
                                </div>
                            </a>
                        </li>
                        <!--<li>
                          <a href='javascript::;'>
                            <i class="menu-icon-zeyn fa fa-user bg-yellow"></i>
                            <div class="menu-info">
                              <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>
                              <p>New phone +1(800)555-1234</p>
                            </div>
                          </a>
                        </li>
                        <li>
                          <a href='javascript::;'>
                            <i class="menu-icon-zeyn fa fa-envelope-o bg-light-blue"></i>
                            <div class="menu-info">
                              <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>
                              <p>nora@example.com</p>
                            </div>
                          </a>
                        </li>
                        <li>
                          <a href='javascript::;'>
                            <i class="menu-icon-zeyn fa fa-envelope-o bg-light-blue"></i>
                            <div class="menu-info">
                              <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>
                              <p>Execution time 5 seconds</p>
                            </div>
                          </a>
                        </li>-->
                    </ul><!-- /.control-sidebar-menu -->

                    <h3 class="control-sidebar-heading"><?php echo $this->translate('216') ?></h3> 
                    <ul class='control-sidebar-menu'>
                        <li>
                            <a href='javascript::;'>               
                                <h4 class="control-sidebar-subheading">
                                    <?php echo $this->translate('534') ?>
                                    <span class="label label-danger pull-right">3%</span>
                                </h4>
                                <div class="progress progress-xxs">
                                    <div class="progress-bar progress-bar-danger" style="width: 3%"></div>
                                </div>                                    
                            </a>
                        </li> 
                        <li>
                            <a href='javascript::;'>               
                                <h4 class="control-sidebar-subheading">
                                    <?php echo $this->translate('535') ?>
                                    <span class="label label-success pull-right">0%</span>
                                </h4>
                                <div class="progress progress-xxs">
                                    <div class="progress-bar progress-bar-success" style="width: 0%"></div>
                                </div>                                    
                            </a>
                        </li> 
                        <li>
                            <a href='javascript::;'>               
                                <h4 class="control-sidebar-subheading">
                                    <?php echo $this->translate('536') ?>
                                    <span class="label label-waring pull-right">0%</span>
                                </h4>
                                <div class="progress progress-xxs">
                                    <div class="progress-bar progress-bar-warning" style="width: 0%"></div>
                                </div>                                    
                            </a>
                        </li> 
                        <!--<li>
                          <a href='javascript::;'>               
                            <h4 class="control-sidebar-subheading">
                              Back End Framework
                              <span class="label label-primary pull-right">68%</span>
                            </h4>
                            <div class="progress progress-xxs">
                              <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
                            </div>                                    
                          </a>
                        </li>-->             
                    </ul><!-- /.control-sidebar-menu -->         

                </div><!-- /.tab-pane -->
                <!-- Stats tab content -->
                <div class="tab-pane" id="control-sidebar-stats-tab"><?php echo $this->translate('537') ?></div><!-- /.tab-pane -->
                <!-- Settings tab content -->
                <div class="tab-pane" id="control-sidebar-settings-tab">            
                    <form method="post">
                        <h3 class="control-sidebar-heading"><?php echo $this->translate('60') ?></h3>
                        <div class="form-group">
                            <label class="control-sidebar-subheading">
                                <?php echo $this->translate('216') ?>
                                <input type="checkbox" class="pull-right" checked />
                            </label>
                            <p>
                                <?php echo $this->translate('538') ?>
                            </p>
                        </div><!-- /.form-group -->

                        <div class="form-group">
                            <label class="control-sidebar-subheading">
                                <?php echo $this->translate('539') ?>
                                <input type="checkbox" class="pull-right" checked />
                            </label>
                            <p>
                                <?php echo $this->translate('68') ?>
                            </p>
                        </div><!-- /.form-group -->

                        <div class="form-group">
                            <label class="control-sidebar-subheading">
                                <?php echo $this->translate('68') ?>
                                <input type="checkbox" class="pull-right" checked />
                            </label>
                            <p>
                                <?php echo $this->translate('68') ?>
                            </p>
                        </div><!-- /.form-group -->

                        <h3 class="control-sidebar-heading"><?php echo $this->translate('67') ?></h3>

                        <div class="form-group">
                            <label class="control-sidebar-subheading">
                                <?php echo $this->translate('68') ?>
                                <input type="checkbox" class="pull-right" checked />
                            </label>                
                        </div><!-- /.form-group -->

                        <div class="form-group">
                            <label class="control-sidebar-subheading">
                                <?php echo $this->translate('69') ?>
                                <input type="checkbox" class="pull-right" />
                            </label>                
                        </div><!-- /.form-group -->

                        <div class="form-group">
                            <label class="control-sidebar-subheading">
                                <?php echo $this->translate('70') ?>
                                <a href="javascript::;" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
                            </label>                
                        </div><!-- /.form-group -->
                    </form>
                </div><!-- /.tab-pane -->
            </div>
        </aside><!-- /.control-sidebar -->
        <!-- Add the sidebar's background. This div must be placed
             immediately after the control sidebar -->
        <div class='control-sidebar-bg'></div>
    </div><!-- ./wrapper -->


    <!--*********************************************************************-->
    <!--************************* Growls section ****************************-->    
    <!--*********************************************************************--> 

    <div id='growls' >

        <!-- New Role Submission growls -->
        <!-- Successful new role submission growl -->
        <div id="growlUI-successfulRoleSubmit" class='growlUI' style="display:none" >    
            <h3><a lang="en" href=""/>Successful Submission</h3>
            <h4><a lang="en" href=""/>Have a nice day!</h4>
        </div>
        <!--// Successful new role submission growl -->

        <!-- New role submission approval growl -->
        <div id="growlUI-newRoleSubmitApproval" class='growlUI' style="display:none" >    
            <h3><a lang="en" href=""/>Do you confirm new role submission?</h3>
            <h4>
                
                <div>
                    <a class="btn btn-success" lang="en" onclick="newRoleSubmissionConfirmation()" >
                    <i class="fa fa-check"></i> Go
                            </a>
                    <a class="btn btn-danger" lang="en" onclick="return newRoleSubmissionRejection();">
                    <i class="fa fa-close"></i> Cancel
                            </a>
                </div>
            </h4>
        </div>
        <!--// New role submission approval growl -->
        
        
        <!-- New passive role submission prevention growl -->
        <div id="growlUI-newPassiveRoleSubmitPrevention" class='growlUI2' style="display:none" >    
            <h3><a lang="en" href=""/>Passive sub-role submission is prohibited!</h3>
            <h4>
                <button type='submit' 
                        id='passiveOk-btn' class="btn btn-success" 
                        onclick="newPassiveRoleSubmissionPrevention()">
                    <i class="fa fa-check"></i><a lang="en" href=""/>Ok
                </button>                
            </h4>
        </div>
        <!--// New passive role submission prevention growl -->
        
        
        

        <!-- Failed new role submission growl -->
        <div id="growlUI-failedRoleSubmit" class='growlUI2' style="display:none" >
            <h3><a lang="en" href=""/>Unsuccessful Submission</h3>
            <h4><a lang="en" href=""/>Error log registered</h4>
        </div>        
        <!--// Failed new role submission growl -->
        
        <!-- Failed new role submission growl -->
        <div id="growlUI-failedRoleSubmit23505" class='growlUI2' style="display:none" >
            <h3><a lang="en" href=""/>Unsuccessful Submission</h3>
            <h4><a lang="en" href=""/>This name is already registered in System.</h4>
            <h4><a lang="en" href=""/>Try another name please!</h4>
        </div>        
        <!--// Failed new role submission growl -->

        <!--// New Role Submission growls -->

        <!--// New Role Submission growls -->

        <!-- ***************************** -->

        <!-- Delete Role Approval growls -->
        <!-- Successful Delete Role growl -->
        <div id="growlUI-roleDeleteApproval" class='growlUI' style="display:none" >    
            <h3><a lang="en" href=""/>Are you sure to delete the role?</h3>
            <h4>
                <button type='submit'
                        id='addNewRoleYes-btn' class="btn btn-success" 
                        onclick="deleteRoleConfirmation()">
                    <i class="fa fa-check"></i><a lang="en" href=""/>Go</button>
                <button type='button' 
                        id='addNewRoleCancel-btn' class="btn btn-danger" 
                        onclick="deleteRoleRejection()">
                    <i class="fa fa-times"></i><a lang="en" href=""/>Cancel</button>
            </h4>
        </div>
        <!--// successful delete role -->
        
        <!-- Delete Role growls -->
        <!-- Successful Delete Role growl -->
        <div id="growlUI-successfulRoleDelete" class='growlUI' style="display:none" >
            <h3><a lang="en" href=""/>Removed...</h3>
        </div>
        <!--// successful delete role -->

        <!-- Failed Delete Role growl -->
        <div id="growlUI-failedRoleDelete" class='growlUI2' style="display:none" >
            <h3><a lang="en" href=""/>Unsuccessful remove operation!</h3>
        </div>
        <!--//Failed Delete Role growl -->
        
        
        <!-- Failed Delete Role growl -->
        <div id="growlUI-failedRoleDeleteNotChecked" class='growlUI2' style="display:none" >
            <h3><a lang="en" href=""/>Unsuccessful remove operation!</h3>
            <h4><a lang="en" href=""/>Please check the role you want to delete!</h4>
        </div>
        <!--//Failed Delete Role growl -->

        <!-- *************************** -->

        <!-- Name Change growls -->
        <!-- Successful Name Change growl -->
        <div id="growlUI-successfulRoleNameChange" class='growlUI'  style="display:none" >
            <h3><a lang="en" href=""/>Successful name change</h3>          
        </div>
        <!--// Successful Name Change growl -->

        <!-- Failed Name Change growl -->
        <div id="growlUI-failedRoleNameChange" class='growlUI2'  style="display:none" >
            <h3><a lang="en" href=""/>Unsuccessful name change</h3>
        </div>
        <!--// Failed Name Change growl -->
        
        <!-- Failed Name Change 23505 error growl -->
        <div id="growlUI-failedRoleNameChange23505" class='growlUI2'  style="display:none" >            
            <h3><a lang="en" href=""/>This name is already registered in System.</h3>
            <h4><a lang="en" href=""/>Try another name please!</h4>
        </div>
        <!--// Failed Name Change 23505 growl -->
        

        <!-- Name Change Approval growl -->
        <div id="growlUI-roleNameChangeApproval" class='growlUI'  style="display:none" >
            <h3><a lang="en" href=""/>Are you sure to change the name?</h3> 
            <h4>
                <button type='submit' 
                        id='roleNameChangeAppYes-btn' class="btn btn-success" 
                        onclick="roleNameChangeConfirmation()">
                    <i class="fa fa-check"></i><a lang="en" href=""/>Go</button>
                <button type='button' 
                        id='roleNameChangeAppCancel-btn' class="btn btn-danger" 
                        onclick="return roleNameChangeRejection();">
                    <i class="fa fa-times"></i><a lang="en" href=""/>Cancel</button>
            </h4>
        </div>
        <!--// Name Change Approval growl -->

        <!-- Null Name Change Warning growl -->
        <div id="growlUI-nullRoleName" class='growlUI2' style="display: none" >
            <h3><a lang="en" href=""/>New name can't be empty</h3>
            <h4><a lang="en" href=""/>Please enter a valid name</h4>            
        </div>        
        <!--// Null Name Change Warning growl -->

        <!-- *************************** -->

        <!-- Activation change growls -->
        <!-- Successful activation change growl -->
        <div id="growlUI-successfulRoleActivationChange" class='growlUI'  style="display:none" >
            <h3><a lang="en" href=""/>Activation changed successfully</h3>          
        </div>
        <!--// Successful activation change growl -->


        <!-- Activation change approval growl -->
        <div id="growlUI-roleActivationChangeApproval" class='growlUI' style="display:none" >
            <h3><a lang="en" href=""/>Are you sure to change the activation?</h3>
            <h4>
                <button type='submit'
                        id='roleActivationChangeAppYes-btn' class="btn btn-success" 
                        onclick="roleActivationChangeConfirmation()">
                    <i class="fa fa-check"></i><a lang="en" href=""/>Go</button>
                <button type='button'
                        id='roleActivationChangeAppCancel-btn' class="btn btn-danger" 
                        onclick="roleActivationChangeRejection()">
                    <i class="fa fa-times"></i><a lang="en" href=""/>Cancel</button>
            </h4>
        </div>
        <!--// Activation change approval growl -->

        <!-- Failed activation change growl -->
        <div id="growlUI-failedRoleActivationChange" class='growlUI2' style="display:none" >
            <h3><a lang="en" href=""/>Activation change failed!</h3>
            <h4></h4>
        </div>
        <!--// Failed activation change growl -->
                
        <!-- Failed activation change growl -->
        <div id="growlUI-failedRoleActivationChange23505" class='growlUI2' style="display:none" >
            <h3><a lang="en" href=""/>Activation change failed!</h3>
            <h4><a lang="en" href=""/>This name is already registered in System.</h4>
        </div>
        <!--// Failed activation change growl -->
        
    </div>

    <!--********************************************************************-->
    <!--//********************* End of growls ******************************-->
    <!--********************************************************************-->




</body>
