<div class="login-box">
    <div class="login-logo">
        <a href="">
            <b>
                <?php echo $this->translate('4') ?>
                <?php echo $this->translate('0') ?> 
            </b> 

        </a>
        <div>
            <p><?php echo $this->translate('570') ?></p>
        </div>
    </div><!-- /.login-logo -->
    
    <div class="col-sm-15">
        <div class="input-group">
            <div class="input-group-addon">
                <i class="fa fa-save"></i>
            </div>
            <button type="button" class="btn btn-default btn-block">
                <?php echo $this->translate('571') ?>
            </button>
        </div>
    </div>
    <div class="col-sm-15">
        <div class="input-group">
            <div class="input-group-addon">
                <i class="fa fa-save"></i>
            </div>
            <button type="button" class="btn btn-default btn-block">
                <?php echo $this->translate('572') ?>
            </button>
        </div>
    </div>
    <div class="col-sm-15">
        <div class="input-group">
            <div class="input-group-addon">
                <i class="fa fa-save"></i>
            </div>
            <button type="button" class="btn btn-default btn-block">
                <?php echo $this->translate('573') ?>
            </button>
        </div>
    </div>
    <div class="col-sm-15">
        <div class="input-group">
            <div class="input-group-addon">
                <i class="fa fa-save"></i>
            </div>
            <button type="button" class="btn btn-default btn-block">                
                <?php echo $this->translate('573') ?>
            </button>
        </div>
    </div>
    <div class="col-sm-15">
        <div class="input-group">
            <div class="input-group-addon">
                <i class="fa fa-save"></i>
            </div>
            <button type="button" class="btn btn-default btn-block">

                <?php echo $this->translate('574') ?>
            </button>
        </div>
    </div>
</div><!-- /.login-box -->