<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('0') . " " . $this->translate('500'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Bootstrap 3.3.4 -->
        <link href="<?php echo $this->basePath('css/bootstrap.min.css') ?>" rel="stylesheet" type="text/css" /> 

        <!-- FontAwesome 4.3.0 -->
        <!--<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />-->
        <link href="<?php echo $this->basePath('plugins/font-awesome-4.4.0/css/font-awesome.min.css') ?>" rel="stylesheet" type="text/css" />

        <!-- Ionicons 2.0.0 -->
        <!--<link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" /> -->   
        <!--<link href="bootstrap/css/ionicons.min.css" rel="stylesheet" type="text/css" />    -->
        <link href="<?php echo $this->basePath('plugins/ionicons-2.0.1/css/ionicons.min.css') ?>" rel="stylesheet" type="text/css" />

        <!-- Theme style -->
        <link href="<?php echo $this->basePath('dist/css/AdminLTE.css') ?>" rel="stylesheet" type="text/css" />
        <!-- AdminLTE Skins. Choose a skin from the css/skins 
             folder instead of downloading all of them to reduce the load. -->
        <link href="<?php echo $this->basePath('dist/css/skins/_all-skins.min.css') ?>" rel="stylesheet" type="text/css" />
        
        <!-- node js Chat Box Css -->
        <link href="<?php echo $this->basePath('dist/css/chat.css') ?>" rel="stylesheet" type="text/css" />

        <!-- Select 2 -->
        <link href="<?php echo $this->basePath('plugins/select2/select2.min.css') ?>" rel="stylesheet" type="text/css" />

        <!-- iCheck -->
        <link href="<?php echo $this->basePath('plugins/iCheck/flat/blue.css') ?>" rel="stylesheet" type="text/css" />
        
        <!-- custom css -->
        <link href="<?php echo $this->basePath('plugins/bahram/bahram.css') ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath('plugins/bahram/balloon.min.css') ?>" rel="stylesheet" type="text/css" />
        
        <!-- bootstrap-modal-nakupanda css -->
        <link href="<?php echo $this->basePath('plugins/bootstrap-modal-nakupanda/bootstrap-dialog.min.css') ?>" rel="stylesheet" type="text/css" />

        <!-- validation engine css -->
        <link href="<?php echo $this->basePath('onyuz/standard/assets/plugins/validationEngine/validationEngine.jquery.css') ?>" rel="stylesheet" type="text/css" />

        <!-- Le styles -->
        <?php /* echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
          ->prependStylesheet($this->basePath('css/style.css'))
          ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
          ->prependStylesheet($this->basePath('css/bootstrap.min.css')) */ ?>

        <!-- Scripts -->
        <?php /* echo $this->headScript()
          ->prependFile($this->basePath('js/bootstrap.min.js'))
          ->prependFile($this->basePath('js/jquery.min.js'))
          ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
          ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
          ; */ ?>

    </head>
    <body class="skin-blue sidebar-mini">

        <?php echo $this->content; ?>

        <?php echo $this->inlineScript() ?>

        <?php
        /* echo $this->headScript()
          ->prependFile($this->basePath('jsinline/dashboard.js'), 'text/javascript')
          ->prependFile($this->basePath('js/bootstrap.min.js'), 'text/javascript')
          ->prependFile($this->basePath('plugins/sparkline/jquery.sparkline.min.js'))
          ->prependFile($this->basePath('plugins/sparkline/jquery.sparkline.min.js'))
          ->prependFile($this->basePath('plugins/jvectormap/jquery-jvectormap-world-mill-en.js'))
          ->prependFile($this->basePath('plugins/jvectormap/jquery-jvectormap-1.2.2.min.js'))
          ->prependFile($this->basePath('plugins/knob/jquery.knob.js'))
          ->prependFile($this->basePath('plugins/daterangepicker/daterangepicker.js'))
          ->prependFile($this->basePath('plugins/daterangepicker/moment.min.js'))
          ->prependFile($this->basePath('plugins/datepicker/bootstrap-datepicker.js'))
          ->prependFile($this->basePath('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js'))
          ->prependFile($this->basePath('plugins/slimScroll/jquery.slimscroll.min.js'))
          ->prependFile($this->basePath('plugins/fastclick/fastclick.min.js'))
          ->prependFile($this->basePath('plugins/zeynel/exPlugs.js'))
          ->prependFile($this->basePath('dist/js/app.js'))
          ->prependFile($this->basePath('dist/js/demo.js'))
          ->prependFile($this->basePath('plugins/zeynel/exPlugs.js'))
          ->prependFile($this->basePath('plugins/jQueryUI/jquery-ui-1.11.2.min.js'))
          ->prependFile($this->basePath('plugins/jQuery/jQuery-2.1.4.min.js'))
          /*->prependFile($this->basePath('plugins/zeynel/exPlugs.js'))
          ->prependFile($this->basePath('plugins/zeynel/exPlugs.js'))
          ->prependFile($this->basePath('plugins/zeynel/exPlugs.js'))
          ->prependFile($this->basePath('plugins/zeynel/exPlugs.js')) */
        //; 
        ?> 

        <!-- jQuery 2.1.4 -->
        <script src="<?php echo $this->basePath('plugins/jQuery/jQuery-2.1.4.min.js') ?>"></script>
        <!-- jQuery UI 1.11.2 -->
        <!--<script src="http://code.jquery.com/ui/1.11.2/jquery-ui.min.js" type="text/javascript"></script>-->
        <script src="<?php echo $this->basePath('plugins/jQueryUI/jquery-ui-1.11.2.min.js') ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('onyuz/standard/assets/plugins/jquery/jquery-migrate.min.js') ?>"></script>
 
        <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
        <script>
            $.widget.bridge('uibutton', $.ui.button);
        </script>
        
        <!-- Bootstrap 3.3.2 JS -->
        <script src="<?php echo $this->basePath('js/bootstrap.min.js') ?>" type="text/javascript"></script>    
               
        <!-- Sparkline -->
        <script src="<?php echo $this->basePath('plugins/sparkline/jquery.sparkline.min.js') ?>" type="text/javascript"></script>
        <!-- jQuery Knob Chart -->
        <script src="<?php echo $this->basePath('plugins/knob/jquery.knob.js') ?>" type="text/javascript"></script>
        <!-- Slimscroll -->
        <script src="<?php echo $this->basePath('plugins/slimScroll/jquery.slimscroll.min.js') ?>" type="text/javascript"></script>
        <!-- FastClick -->
        <script src='<?php echo $this->basePath('plugins/fastclick/fastclick.min.js') ?>'></script>
        <!-- Zeynel plugins -->
        <script src='<?php echo $this->basePath('plugins/zeynel/exPlugs.js') ?>'></script>
        <!-- AdminLTE App -->
        <script src="<?php echo $this->basePath('dist/js/app.js') ?>" type="text/javascript"></script>    
        <!-- AdminLTE for demo purposes -->
        <script src="<?php echo $this->basePath('dist/js/demo.js') ?>" type="text/javascript"></script>

        <!-- AdminLTE for demo purposes -->
        <!--<script src="plugins/validationEngine/jquery.validationEngine-en.js" type="text/javascript"></script>
        <script src="plugins/validationEngine/jquery.validationEngine.js" type="text/javascript"></script>-->

        <!-- multulanguage js -->
        <script src="<?php echo $this->basePath('plugins/jquery-lang-js-master/js.cookie.js') ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('plugins/jquery-lang-js-master/jquery-lang.js') ?>" type="text/javascript"></script>
        <!--<script src="js/langpack/nonDynamic.js" charset="utf-8" type="text/javascript"></script>-->
        <!-- Form validation js -->
        <script src="<?php echo $this->basePath('onyuz/standard/assets/plugins/validationEngine/jquery.validationEngine-' . $this->layout()->test . '.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('onyuz/standard/assets/plugins/validationEngine/jquery.validationEngine-en.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('onyuz/standard/assets/plugins/validationEngine/jquery.validationEngine.js') ?>" type="text/javascript"></script>
        <!-- Select2 -->
        <script src="<?php echo $this->basePath('plugins/select2/select2.full.js') ?>" type="text/javascript"></script>
        <!--ddslick dropdown js-->
        <script type="text/javascript" src="<?php echo $this->basePath('plugins/bootstrap-select-ddslick/js/ddslick.min.js') ?>"></script>
        
        <!--inputmask js-->
        <script type="text/javascript" src="<?php echo $this->basePath('plugins/input-mask/jquery.inputmask.js') ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath('plugins/input-mask/jquery.inputmask.extensions.js') ?>"></script>
        
        <!-- opentok video chat  -->
        <script src="https://static.opentok.com/v2/js/opentok.js" charset="utf-8"></script>
        
        <!-- sayfa içine yazılan js'ler ekleniyor-->
        <script src="<?php echo $this->basePath('jsinline/sanalfabrika_cpgenelset.js') ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('jsinline/firm_all_consults.js') ?>" type="text/javascript"></script>
        
        <!-- leftMenuFunction Js-->
        <script src="<?php echo $this->basePath('jsinline/languageBar.js') ?>"></script>   
        <script src="<?php echo $this->basePath('jsinline/leftMenuFunction.js') ?>" type="text/javascript"></script>
        <!-- Custom Plugins-->
        <script src="<?php echo $this->basePath('plugins/bahram/exPlugs.js') ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('plugins/bahram/loging.js') ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('plugins/bahram/image_upload.js') ?>" type="text/javascript"></script>
        <!-- bootstrap-modal-nakupanda ekleniyor-->
        <script src="<?php echo $this->basePath('plugins/bootstrap-modal-nakupanda/bootstrap-dialog.min.js') ?>" type="text/javascript"></script>
        
                <!--socket.io client-->
        <script src="<?php echo $this->basePath('node_js/node_modules/socket.io-client/dist/socket.io.js') ?>" type="text/javascript"></script>
        <script>
            $.widget.bridge('uibutton', $.ui.button);
            
            $(document).ready(function () {
                /*prepareDynamicDates();
                $(".time").timeago();*/
                
                /*jQuery("time.timeago").timeago();
                jQuery.timeago.settings.allowFuture = true;*/
                
                var chatWidget = $('#send-message').chatBoard({
                    ioSocket : io.connect('https://10.18.2.206:8444'),
                });
                chatWidget.chatBoard('setFormSubmit');
                chatWidget.chatBoard('socketListen');
                
                
                //video chat
                var apiKey = '45752452';
                var sessionId = '2_MX40NTc1MjQ1Mn5-MTQ4NDg5MjgzNzQ4MX5xSlBFaFBIcnFlZitZVzNkZ0JlTnBIQnJ-UH4';
                var token = 'T1==cGFydG5lcl9pZD00NTc1MjQ1MiZzaWc9N2M4ZTBjNDZjMDI2ODk4YWI1N2YwMzBjOWUwNTJlMjY0MDY0MTVmYTpzZXNzaW9uX2lkPTJfTVg0ME5UYzFNalExTW41LU1UUTRORGc1TWpnek56UTRNWDV4U2xCRmFGQkljbkZsWml0WlZ6TmtaMEpsVG5CSVFuSi1VSDQmY3JlYXRlX3RpbWU9MTQ4NDg5Mjk1NCZub25jZT0wLjQ5OTY0MzkwNDExOTc4NDQzJnJvbGU9cHVibGlzaGVyJmV4cGlyZV90aW1lPTE0ODc0ODQ5NTU=';

                $.AdminLTE.boxWidget.collapse($("#chatPanelRemote"));
                $.AdminLTE.boxWidget.collapse($("#chatPanel"));
                var controller = false;
                var session;
                $('#chatter').on('click', function(e){
                    //alert('test');
                    
                    var numerator = 0;
                    if(controller==false){
                        controller = true;
                        $.AdminLTE.boxWidget.collapse($("#chatPanel"));
                        $.AdminLTE.boxWidget.collapse($("#chatPanelRemote"));
                        session = OT.initSession(apiKey, sessionId)  
                            .on('streamCreated', function(event) {
                            //console.log('session created');
                            //if(numerator==0){
                            //numerator++;
                            session.subscribe(event.stream, 'publisherRemote',{
                                  insertMode: 'append',
                                  width: '100%',
                                  height: '100%'}); 
                                
                            //}   
                            })
                            .connect(token, function(error) {
                                
                                    var publisher = OT.initPublisher('publisher', {
                                                insertMode: 'append',
                                                width: '100%',
                                                height: '100%'});
                                    session.publish(publisher);
                                
                                
                            });
                        $('html, body').animate({
                            scrollTop: $("#chatPanel").offset().top
                        }, 2000);
                        
                    } else if(controller==true) {
                        //alert('test true');
                        controller = false;
                        $.AdminLTE.boxWidget.collapse($("#chatPanelRemote"));
                        $.AdminLTE.boxWidget.collapse($("#chatPanel"));
                        session.disconnect();
                    }
                    
                    
                });

            });

        </script>

    </body>
</html>
