<!DOCTYPE html>
<input id="requestUriRegulated" type="hidden"  value="<?php echo $this->requestUriRegulated; ?>"></input>
<input id="langCode" type="hidden"  value="<?php echo $this->langCode; ?>"></input>
<input id="pk" type="hidden"  value="<?php echo $this->publicKey; ?>"></input>
<input id="selectedCompanyNpk" type="hidden"  value="<?php echo $this->selectedCompanyNpk; ?>"></input>
<input id="selectedCompanyShN" type="hidden" value="<?php echo $this->selectedCompanyShN; ?>"></input>
<input id="controller" type="hidden"  value="<?php echo $this->layout()->controller; ?>"></input>
<input id="module" type="hidden"  value="<?php echo $this->layout()->module; ?>"></input>

<!--=== Style Switcher ===-->    
<i class="style-switcher-btn fa fa-cogs hidden-xs"></i>
<div class="style-switcher animated fadeInRight">
    <div class="style-swticher-header">
        <div class="style-switcher-heading">Style Switcher</div>            
        <div class="theme-close"><i class="icon-close"></i></div>
    </div>

    <div class="style-swticher-body">
        <!-- Theme Colors -->
        <div class="style-switcher-heading">Theme Colors</div>
        <ul class="list-unstyled">
            <li class="theme-default theme-active" data-style="default" data-header="light"></li>
            <li class="theme-blue" data-style="blue" data-header="light"></li>
            <li class="theme-orange" data-style="orange" data-header="light"></li>
            <li class="theme-red" data-style="red" data-header="light"></li>
            <li class="theme-light" data-style="light" data-header="light"></li>
            <li class="theme-purple last" data-style="purple" data-header="light"></li>
            <li class="theme-aqua" data-style="aqua" data-header="light"></li>
            <li class="theme-brown" data-style="brown" data-header="light"></li>
            <li class="theme-dark-blue" data-style="dark-blue" data-header="light"></li>
            <li class="theme-light-green" data-style="light-green" data-header="light"></li>
            <li class="theme-dark-red" data-style="dark-red" data-header="light"></li>
            <li class="theme-teal last" data-style="teal" data-header="light"></li>
        </ul>

        <!-- Theme Skins -->
        <div class="style-switcher-heading">Theme Skins</div>
        <div class="row no-col-space margin-bottom-20 skins-section">
            <div class="col-xs-6">
                <button data-skins="default" class="btn-u btn-u-xs btn-u-dark btn-block active-switcher-btn handle-skins-btn">Light</button>
            </div>
            <div class="col-xs-6">
                <button data-skins="dark" class="btn-u btn-u-xs btn-u-dark btn-block skins-btn">Dark</button>
            </div>
        </div>            

        <hr>

        <!-- Layout Styles -->
        <div class="style-switcher-heading">Layout Styles</div>
        <div class="row no-col-space margin-bottom-20">
            <div class="col-xs-6">
                <a href="javascript:void(0);" class="btn-u btn-u-xs btn-u-dark btn-block active-switcher-btn wide-layout-btn">Wide</a>                
            </div>
            <div class="col-xs-6">
                <a href="javascript:void(0);" class="btn-u btn-u-xs btn-u-dark btn-block boxed-layout-btn">Boxed</a>                
            </div>
        </div>            

        <hr>

        <!-- Theme Type -->
        <div class="style-switcher-heading">Theme Types and Versions</div>
        <div class="row no-col-space margin-bottom-10">
            <div class="col-xs-6">
                <a href="Shop-UI/index.html" class="btn-u btn-u-xs btn-u-dark btn-block">Shop UI <small class="dp-block">Template</small></a>
            </div>
            <div class="col-xs-6">
                <a href="One-Page/index.html" class="btn-u btn-u-xs btn-u-dark btn-block">One Page <small class="dp-block">Template</small></a>
            </div>
        </div>           

        <div class="row no-col-space">
            <div class="col-xs-6">
                <a href="Blog/index.html" class="btn-u btn-u-xs btn-u-dark btn-block">Blog <small class="dp-block">Template</small></a>
            </div>
            <div class="col-xs-6">
                <a href="RTL/index.html" class="btn-u btn-u-xs btn-u-dark btn-block">RTL <small class="dp-block">Version</small></a>
            </div>
        </div>           
    </div>
</div><!--/style-switcher-->
<!--=== End Style Switcher ===-->   

<div class="wrapper">
    <!--=== Header ===-->     
    <div class="header">
        <div class="container">
            <!-- Logo -->
            <a class="logo" href="<?php echo $this->url('sanalfabrika', array('action' => 'index', 'lang' => $this->langCode)); ?>">
                <img src="<?php echo $this->basePath('onyuz/standard/assets/img/logo1-default.png') ?>" alt="Logo">
            </a>
            <!-- End Logo -->

            <!-- Topbar -->
            <div class="topbar">
                <ul class="loginbar pull-right">
                    <li id="user_profile_link" onmouseover='showuserdetails()' onmouseout="hideuserdetails()"
                        style="visibility: hidden; display: none" unpk="">
                        <a style="cursor: pointer;" onclick="setredirectprofile()" >
                            <img id="user_image_ph" style="max-height: 20px; margin-right: 10px" 
                                 class="rounded-2x" src="" alt="">                            
                            <span id='user_name'></span>
                        </a>
                        <!-- user info -->
                        <div class="rounded-2x user_details_header" id='user_detailed_info_bulb'>
                            <div class="row">
                                <div class="col-sm-2">
                                    <img id="user_image_ph_hover" style="max-height: 60px; margin: 5px;" 
                                         class="rounded-2x" src="" alt="">
                                </div>
                                <div class="col-sm-10">
                                    <span class="col-sm-6"><?php echo $this->translate('111') ?>:</span>
                                    <span class="col-sm-6" id='user_name_hover'></span>
                                    <br/>
                                    <span class="col-sm-6"><?php echo $this->translate('595') ?>:</span>
                                    <span class="col-sm-6" id='user_membership'></span>
                                    <br/>
                                    <span class="col-sm-6"><?php echo $this->translate('596') ?>:</span>
                                    <span class="col-sm-6" id='user_reg_date'></span><br/>
                                </div>            
                            </div>
                            <div class="row">
                                <div class="heading heading-v6">
                                    <h2 style="font-size: 12px"><?php echo $this->translate('597') ?></h2>
                                </div>
                            </div>
                            <div class="row" style="margin-left:20px; font-size: 12px">
                                    <div class="row">
                                        <a href=''>
                                        <i class="fa fa-user"></i>
                                            <?php echo $this->translate('598') ?>
                                        </a>
                                    </div>
                                    <br/>  
                                    <div class="row">
                                        <a href=''>
                                            <i class="fa fa-gear"></i>
                                                <?php echo $this->translate('599') ?>
                                        </a>
                                    </div>
                                    <br/>
                            </div>
                        </div>
                        <!--/user info --> 
                    </li>                                        
                    <li id="user_profile_link_divider" class="topbar-devider" style="visibility: hidden; display: none"></li>
                    <li class="hoverSelector" id="setting_link" style="visibility: hidden; display: none">
                        <a id="setting_link_a" href="" style="cursor: pointer;"><?php echo $this->translate('600') ?></a>
                        <i class="fa fa-gear"></i>
                        <ul id='topCompaniesBar' class="companies hoverSelectorBlock"> 
                            <li>
                                <a href="">
                                <?php echo $this->translate('601')?>
                                </a>
                            </li>
                            <li>
                                <a href="">
                                <?php echo $this->translate('602')?>
                                </a>
                            </li>
                        </ul>
                    </li>                        
                    <li id="setting_link_divider" class="topbar-devider" style="visibility: hidden; display: none"></li>
                    <li class="hoverSelector">
                        <a><?php echo $this->translate('91') ?> </a>
                        <i class="fa fa-globe"></i>
                        <ul id='topLanguageBar' class="languages hoverSelectorBlock">                                    
                        </ul>
                    </li>
                    <li class="topbar-devider"></li>   
                    <li><a href="<?php echo $this->url('sanalfabrika', array('action' => 'index', 'lang' => $this->langCode)); ?>"><?php echo $this->translate('89') ?></a></li>  
                    <li class="topbar-devider"></li>   
                    <li id="login_place" style="visibility: hidden; display: none">
                        <a href="<?php echo $this->url('sanalfabrika', array('action' => 'login', 'lang' => $this->langCode)); ?>">
                            <span>
                                <?php echo $this->translate('30') ?>
                            </span>
                        </a>
                    </li>
                    <li id="logout_place" style="visibility: hidden; display: none">
                        <a href="<?php echo $this->url('login', array('action' => 'logout', 'lang' => $this->langCode)); ?>">
                            <span>
                                <?php echo $this->translate('31') ?>
                            </span>
                        </a>
                    </li>
                    <!--<li><a href="<?php echo $this->url('login', array('action' => 'logout')); ?>"><span id="loging_ph"></span></a></li>-->   
                </ul>
            </div>
            <!-- End Topbar -->



            <!-- Toggle get grouped for better mobile display -->
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="fa fa-bars"></span>
            </button>
            <!-- End Toggle -->
        </div><!--/end container-->

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse menu-xs navbar-responsive-collapse" >
            <div class="container">
                <ul class="nav navbar-nav " style="font-size: 10px;">
                    <li class="page-scroll home">
                        <a href="<?php echo $this->url('sanalfabrika', array('action' => 'index', 'lang' => $this->langCode));
                                ?>#body"><?php echo $this->translate('9') ?></a>
                    </li>
                    <li class="page-scroll">
                        <a href="<?php echo $this->url('sanalfabrika', array('action' => 'index', 'lang' => $this->langCode));
                                ?>#about"><?php echo $this->translate('229') ?></a>
                    </li>
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                            <?php echo $this->translate('230') ?>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="page-scroll"><a href="<?php echo $this->url('sanalfabrika', array('action' => 'index', 'lang' => $this->langCode));
                            ?>#ostimServices">
                                    <?php echo $this->translate('15') ?></a>
                            </li>
                        </ul>
                    </li>
                    <li class="page-scroll">
                        <a href="<?php echo $this->url('sanalfabrika', array('action' => 'index', 'lang' => $this->langCode));
                                    ?>#news"><?php echo $this->translate('231') ?></a>
                    </li>
                    <li class="page-scroll">
                        <a href="<?php echo $this->url('sanalfabrika', array('action' => 'index', 'lang' => $this->langCode));
                                    ?>#contact"><?php echo $this->translate('232') ?></a>
                    </li>
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                            <?php echo $this->translate('0') ?>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="page-scroll">
                                <a href="<?php echo $this->url('sanalfabrika', array('action' => 'clientspage', 'lang' => $this->langCode)); ?>">
                                    <?php echo $this->translate('345') ?>
                                </a>
                            </li>
                            <li class="page-scroll">
                                <a href="<?php echo $this->url('sanalfabrika', array('action' => 'sfmachines', 'lang' => $this->langCode)); ?>">
                                    <?php echo $this->translate('446') ?>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div><!--/end container-->
        </div><!--/navbar-collapse-->
    </div>
    <!--=== End Header ===-->




    <!--=== Breadcrumbs ===-->
    <div class="breadcrumbs">
        <!--<div style='background: #FAF8F0;' class="container">--> 
        <div style='background: #E0EDDF;' class="container">
            <h1 class="pull-left"><i class="fa fa-user"></i><?php echo $this->translate('345') ?></h1>
            <ul class="pull-right breadcrumb">                        
                <li>
                    <a href="<?php echo $this->url('sanalfabrika', array('action' => 'index', 'lang' => $this->langCode));
                                    ?>">
                           <?php echo $this->translate('9') ?>
                    </a>
                </li>
                <li class="active"><?php echo $this->translate('345') ?></li>
            </ul>
        </div>
    </div><!--/breadcrumbs-->
    <!--=== End Breadcrumbs ===-->

    <!--=== Content Part ===-->
    <div class="container content">		
        <div class="row">
            <div id="clients_left_side" class="col-md-9 box box-relative">
                <div class="tag-box tag-box-v3" style="box-shadow: 0 0 30px #7c8082;">
                    <div class="row" id='search_box' data-toggle="tooltip" data-placement="top" 
                         title="Click to open/close search box">
                        <div  onmouseover="" style="cursor: pointer;" 
                              class="headline" onclick='hide_search()'>
                            <h2>
                                <i class="fa fa-search"></i>
                                <?php echo $this->translate('518') ?>
                            </h2>
                        </div>
                        <form class="sky-form" id='search_box' status='opened'>
                            <fieldset style="padding: 9px 25px 5px;">    
                                <div class="row">
                                    <!--<div class="col-md-6">-->
                                    <section>
                                        <label class="label">
                                            <?php echo $this->translate('206') ?>
                                        </label>
                                        <div class="input-group">
                                            <div class="input-group-addon">
                                                <i class="fa fa-tag"></i>
                                            </div>
                                            <input type="text" name="company_name" 
                                                   id="company_name" 
                                                   class="form-control validate[required,custom[onlyLetterSp]]">
                                        </div>
                                    </section>
                                    <section>
                                        <label class="label">
                                            <?php echo $this->translate('519') ?>
                                        </label>
                                        <div class="input-group">
                                            <div class="input-group-addon">
                                                <i class="fa fa-pie-chart"></i>
                                            </div>
                                            <div id="dropdownSectors"></div>
                                        </div>
                                    </section>
                                    <!--                                    </div>    
                                                                        <div class="col-md-6">-->
                                    <section>
                                        <label class="label">
                                            <?php echo $this->translate('135') ?>
                                        </label>
                                        <div class="input-group">
                                            <div class="input-group-addon">
                                                <i class="fa fa-globe"></i>
                                            </div>
                                            <div id="dropdownCountries"></div>
                                        </div>
                                    </section>
<!--                                        <section>
                                        <label class="label">
                                    <?php echo $this->translate('138') ?>
                                        </label>
                                        <div class="input-group">
                                            <div class="input-group-addon">
                                                <i class="fa fa-building"></i>
                                            </div>
                                            <input type="text" name="company_city" 
                                                   id="company_city"
                                                   class="form-control validate[required,custom[onlyLetterSp]]">
                                        </div>
                                    </section>-->
                                    <!--</div>-->
                                </div>
                                <div class="row">
                                    <section>
                                        <button type="button" id="search_btn" 
                                                class="btn-u btn-u-dark-blue" 
                                                onclick="searchCompanies()">   
                                                    <?php echo $this->translate('520') ?>                                                
                                        </button>
                                        <button type="button" id="reset_btn" 
                                                class="btn-u" 
                                                onclick="resetForm()">
                                                    <?php echo $this->translate('186') ?>
                                        </button>
                                    </section>
                                </div>
                            </fieldset>
                        </form>

                        <!--<div class="col-md-3">
                            <h2 class="heading-sm">Emphasis Classes</h2>
                            <p class="muted">Muted Textxt Information</p>
                            <p class="text-primary">Primary Textxt Information</p>
                            <p class="text-success">Success Textxt Information</p>
                            <p class="text-warning">Warning Textxt Information</p>
                            <p class="text-danger">Danger Textxt Information</p>
                            <p class="text-info">Info Textxt Information</p>
                            <p class="text-success">Success Textxt Information</p>
                        </div>
                        <div class="col-md-3">
                            <h2 class="heading-sm">Address</h2>
                            <address>
                                <strong>Twitter, Inc.</strong><br>
                                795 Folsom Ave, Suite 600<br>
                                San Francisco, CA 94107<br>
                                <abbr title="Phone">P:</abbr> (123) 456-7890
                            </address>
                            <address>
                                <strong>Full Name</strong><br>
                                <a href="mailto:#">first.last@example.com</a>
                            </address>
                        </div>
                        <div class="col-md-6">
                            <h2 class="heading-sm">Misc Collection</h2>
                            <p>Lorem Ipsum is simply dummy text and <a href="#">here is a link example.</a></p>
                            <p><del>Use a tag del lorem Ipsum is simply dummy text</del></p>
                            <p>Some <sup>sup example</sup> and some more <sub>sub example</sub></p>
                            <p><abbr title="attribute">attr distribution</abbr> of letters as opposed <abbr title="attribute">attr</abbr> to using</p>
                            <p><span style="text-decoration: underline;">Use a tag span lorem Ipsum is simply dummy text</span></p>                            
                        </div>-->
                    </div><!--/row-->
                </div>

                <div id="come_here" class="headline"><h2><?php echo $this->translate('344') ?></h2></div>

                <!-- Start Clients Block-->
                <div id="pagination_content" class='box box-relative'>

                </div>
                <!-- End Clients Block-->


                <!-- pagination bar -->
                <div class="row clients-page" style="text-align: center">
                    <div class="demo demo4_bottom" id="paginationBar"></div>
                </div>
                <!--// End of Pagination bar -->
            </div><!--/col-md-9-->



            <div class="col-md-3">
                <!-- Our Services -->
                <div class="who margin-bottom-30">
                    <div class="headline"><h2><?php echo $this->translate('104') ?></h2></div>
                    <p><?php echo $this->translate('382') ?></p>
                    <ul class="list-unstyled">
                        <li><a href="#"><i class="fa fa-unlock"></i><?php echo $this->translate('383') ?></a></li>
                        <li><a href="#"><i class="fa fa-child"></i><?php echo $this->translate('384') ?></a></li>
<!--                        <li><a href="#"><i class="fa fa-arrow-circle-right"></i><?php echo $this->translate('385') ?></a></li>
                        <li><a href="#"><i class="fa fa-arrow-circle-right"></i><?php echo $this->translate('386') ?></a></li>
                        <li><a href="#"><i class="fa fa-arrow-circle-right"></i><?php echo $this->translate('387') ?></a></li>-->
                        <li><a href="#"><i class="fa fa-print"></i><?php echo $this->translate('388') ?></a></li>
                    </ul>
                </div>


                <!-- About Us -->
                <div class="headline"><h2><?php echo $this->translate('229') ?></h2></div>
                <div class="margin-bottom-30">                    
                    <p><?php echo $this->translate("389") ?></p>
                </div>

                <!-- Contact Us -->
                <div class="who margin-bottom-30">
                    <div class="headline"><h2><?php echo $this->translate('110') ?></h2></div>
                    <p><?php echo $this->translate('469') ?></p>
                    <ul class="list-unstyled">
                        <li><a href="#"><i class="fa fa-home"></i>100. Yıl Bulvarı No: 101/A<br/>
                                OSTIM Ankara <br/>
                                Turkey</a></li>
                        <li><i class="fa fa-envelope-o"></i><?php echo $this->translate('112') ?>:<a href="#"> info@ostim.com.tr</a></li>
                        <li><i class="fa fa-phone"></i><?php echo $this->translate('147') ?>: <a href="#">312 385 50 90</a></li>
                        <li><i class="fa fa-fax"></i><?php echo $this->translate('148') ?>: <a href="#">312 354 58 98</a></li>
                        <li><i class="fa fa-globe"></i><?php echo $this->translate('130') ?>: <a target='_blank' href="http://www.ostimteknoloji.com">http://www.ostimteknoloji.com</a></li>
                    </ul>
                </div>
            </div><!--/col-md-3-->
        </div><!--/row-->        
    </div><!--/container-->		
    <!--=== End Content Part ===-->

    <!--=== Footer Version 1 ===-->
    <div class="footer-v1">
        <div class="footer">
            <div class="container">
                <div class="row">
                    <!-- About -->
                    <div class="col-md-3 md-margin-bottom-40">
                        <a href="index.phtml"><img id="logo-footer" class="footer-logo" 
                                                   src="<?php echo $this->basePath('onyuz/standard/assets/img/logo2-default.png') ?>" 
                                                   alt=""></a>
                        <p><?php echo $this->translate('264') ?></p>
                    </div><!--/col-md-3-->
                    <!-- End About -->

                    <!-- Latest -->
                    <div class="col-md-3 md-margin-bottom-40">
                        <div class="posts">
                            <div class="headline"><h2><?php echo $this->translate('261') ?></h2></div>
                            <ul class="list-unstyled latest-list">
                                <li>
                                    <a href="#"><?php echo $this->translate('265') ?></a>
                                    <small><?php echo $this->translate('286') ?> 8, 2016</small>
                                </li>
                                <li>
                                    <a href="#"><?php echo $this->translate('266') ?></a>
                                    <small><?php echo $this->translate('285') ?> 23, 2016</small>
                                </li>
                                <li>
                                    <a href="#"><?php echo $this->translate('267') ?></a>
                                    <small><?php echo $this->translate('296') ?> 15, 2016</small>
                                </li>
                            </ul>
                        </div>
                    </div><!--/col-md-3-->  
                    <!-- End Latest --> 

                    <!-- Link List -->
                    <div class="col-md-3 md-margin-bottom-40">
                        <div class="headline"><h2><?php echo $this->translate('262') ?></h2></div>
                        <ul class="list-unstyled link-list">
                            <li><a href="http://www.ostim.org.tr/"><?php echo $this->translate('268') ?></a><i class="fa fa-angle-right"></i></li>
                            <li><a href="http://www.sanayi.gov.tr/"><?php echo $this->translate('269') ?></a><i class="fa fa-angle-right"></i></li>
                            <li><a href="https://www.tubitak.gov.tr/"><?php echo $this->translate('270') ?></a><i class="fa fa-angle-right"></i></li>
                            <li><a href="http://www.kosgeb.gov.tr/"><?php echo $this->translate('271') ?></a><i class="fa fa-angle-right"></i></li>
                            <!--<li><a href="#"><?php echo $this->translate('') ?></a><i class="fa fa-angle-right"></i></li>-->
                        </ul>
                    </div><!--/col-md-3-->
                    <!-- End Link List -->                    

                    <!-- Address -->
                    <div class="col-md-3 map-img md-margin-bottom-40">
                        <div class="headline"><h2><?php echo $this->translate('110') ?></h2></div>                         
                        <address class="md-margin-bottom-40">
                            100. Yıl Bulvarı No: 101/A <br />
                            OSTIM, Ankara <br />
                            Turkey <br />
                            <?php echo $this->translate('147') ?> :  +90 312 385 50 90 <br />
                            <?php echo $this->translate('148') ?>:    +90 312 354 58 98 <br />
                            <?php echo $this->translate('112') ?>: <a href="mailto:info@ostim.com.tr" class="">info@ostim.com.tr</a>
                        </address>
                    </div><!--/col-md-3-->
                    <!-- End Address -->
                </div>
            </div> 
        </div><!--/footer-->

        <div class="copyright">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">                     
                        <p>
                            2016 &copy; <?php echo $this->translate('274') ?>
                            <a href="#"><?php echo $this->translate('273') ?></a> | <a href="#"><?php echo $this->translate('272') ?></a>
                        </p>
                    </div>

                    <!-- Social Links -->
                    <div class="col-md-6">
                        <ul class="footer-socials list-inline">
                            <li>
                                <a href="https://www.facebook.com/OstimOSB/" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Facebook">
                                    <i class="fa fa-facebook"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Skype">
                                    <i class="fa fa-skype"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://plus.google.com/+OST%C4%B0MOSB1967" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Google Plus">
                                    <i class="fa fa-google-plus"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://www.linkedin.com/in/ostim-osb-2b94b847" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Linkedin">
                                    <i class="fa fa-linkedin"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://www.instagram.com/ostimosb/" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Instagram">
                                    <i class="fa fa-instagram"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://twitter.com/ostimosb" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Twitter">
                                    <i class="fa fa-twitter"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Dribbble">
                                    <i class="fa fa-dribbble"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <!-- End Social Links -->
                </div>
            </div> 
        </div><!--/copyright-->
    </div>    
    <!--=== End Footer Version 1 ===-->
</div><!--/wrapper-->
