<!DOCTYPE html>
<input id="requestUriRegulated" type="hidden"  value="<?php echo $this->requestUriRegulated; ?>"></input>
<input id="langCode" type="hidden"  value="<?php echo $this->langCode; ?>"></input>
<input id="pk" type="hidden"  value="<?php echo $this->publicKey; ?>"></input>
<input id="selectedCompanyNpk" type="hidden"  value="<?php echo $this->selectedCompanyNpk; ?>"></input>
<input id="selectedCompanyShN" type="hidden"  value="<?php echo $this->selectedCompanyShN; ?>"></input>
<input id="controller" type="hidden"  value="<?php echo $this->layout()->controller; ?>"></input>
<input id="module" type="hidden"  value="<?php echo $this->layout()->module; ?>"></input>


<!--=== Style Switcher ===-->    
<i class="style-switcher-btn fa fa-cogs hidden-xs"></i>
<div class="style-switcher animated fadeInRight">
    <div class="style-swticher-header">
        <div class="style-switcher-heading">Style Switcher</div>            
        <div class="theme-close"><i class="icon-close"></i></div>
    </div>

    <div class="style-swticher-body">
        <!-- Theme Colors -->
        <div class="style-switcher-heading">Theme Colors</div>
        <ul class="list-unstyled">
            <li class="theme-default theme-active" data-style="default" data-header="light"></li>
            <li class="theme-blue" data-style="blue" data-header="light"></li>
            <li class="theme-orange" data-style="orange" data-header="light"></li>
            <li class="theme-red" data-style="red" data-header="light"></li>
            <li class="theme-light" data-style="light" data-header="light"></li>
            <li class="theme-purple last" data-style="purple" data-header="light"></li>
            <li class="theme-aqua" data-style="aqua" data-header="light"></li>
            <li class="theme-brown" data-style="brown" data-header="light"></li>
            <li class="theme-dark-blue" data-style="dark-blue" data-header="light"></li>
            <li class="theme-light-green" data-style="light-green" data-header="light"></li>
            <li class="theme-dark-red" data-style="dark-red" data-header="light"></li>
            <li class="theme-teal last" data-style="teal" data-header="light"></li>
        </ul>

        <!-- Theme Skins -->
        <div class="style-switcher-heading">Theme Skins</div>
        <div class="row no-col-space margin-bottom-20 skins-section">
            <div class="col-xs-6">
                <button data-skins="default" class="btn-u btn-u-xs btn-u-dark btn-block active-switcher-btn handle-skins-btn">Light</button>
            </div>
            <div class="col-xs-6">
                <button data-skins="dark" class="btn-u btn-u-xs btn-u-dark btn-block skins-btn">Dark</button>
            </div>
        </div>            

        <hr>

        <!-- Layout Styles -->
        <div class="style-switcher-heading">Layout Styles</div>
        <div class="row no-col-space margin-bottom-20">
            <div class="col-xs-6">
                <a href="javascript:void(0);" class="btn-u btn-u-xs btn-u-dark btn-block active-switcher-btn wide-layout-btn">Wide</a>                
            </div>
            <div class="col-xs-6">
                <a href="javascript:void(0);" class="btn-u btn-u-xs btn-u-dark btn-block boxed-layout-btn">Boxed</a>                
            </div>
        </div>            

        <hr>

        <!-- Theme Type -->
        <div class="style-switcher-heading">Theme Types and Versions</div>
        <div class="row no-col-space margin-bottom-10">
            <div class="col-xs-6">
                <a href="Shop-UI/index.html" class="btn-u btn-u-xs btn-u-dark btn-block">Shop UI <small class="dp-block">Template</small></a>
            </div>
            <div class="col-xs-6">
                <a href="One-Page/index.html" class="btn-u btn-u-xs btn-u-dark btn-block">One Page <small class="dp-block">Template</small></a>
            </div>
        </div>           

        <div class="row no-col-space">
            <div class="col-xs-6">
                <a href="Blog/index.html" class="btn-u btn-u-xs btn-u-dark btn-block">Blog <small class="dp-block">Template</small></a>
            </div>
            <div class="col-xs-6">
                <a href="RTL/index.html" class="btn-u btn-u-xs btn-u-dark btn-block">RTL <small class="dp-block">Version</small></a>
            </div>
        </div>           
    </div>
</div><!--/style-switcher-->
<!--=== End Style Switcher ===-->    

<div class="wrapper">
    <!--=== Header ===-->   
    <div class="header">
        <div class="container">
            <!-- Logo -->
            <a class="logo" href="<?php echo $this->url('sanalfabrika', array('action' => 'index','lang'=> $this->langCode)); ?>">
                <img src="<?php echo $this->basePath('onyuz/standard/assets/img/logo1-default.png') ?>" alt="Logo">
            </a>
            <!-- End Logo -->

            <!-- Topbar -->
            <div class="topbar">
                <ul style="background: #ddd;
                    padding: 10px;" class="loginbar pull-right">
                    <li id="setting_link" style="visibility: hidden; display: none">
                        <a style="cursor: pointer;" onclick="setredirect()"><?php echo $this->translate('490') ?></a></li>                                        
                    <li id="setting_link_divider" class="topbar-devider" style="visibility: hidden; display: none"></li>
                    <li class="hoverSelector">
                        <a><?php echo $this->translate('91') ?> </a>
                        <i class="fa fa-globe"></i>
                        <ul id='topLanguageBar' class="languages hoverSelectorBlock">                                    
                        </ul>
                    </li>
                    <li class="topbar-devider"></li>   
                    <li><a href="<?php echo $this->url('sanalfabrika', array('action' => 'index','lang'=> $this->langCode)); ?>"><?php echo $this->translate('89') ?></a></li>  
                    <li class="topbar-devider"></li>   
                    <li id="login_place" style="visibility: hidden; display: none">
                        <a href="<?php echo $this->url('sanalfabrika', array('action' => 'login','lang'=> $this->langCode)); ?>">
                            <span>
                                <?php echo $this->translate('30')?>
                            </span>
                        </a>
                    </li>
                    <li id="logout_place" style="visibility: hidden; display: none">
                        <a href="<?php echo $this->url('login', array('action' => 'logout','lang'=> $this->langCode)); ?>">
                            <span>
                                <?php echo $this->translate('31')?>
                            </span>
                        </a>
                    </li>
                    <!--<li><a href="<?php echo $this->url('login', array('action' => 'logout')); ?>"><span id="loging_ph"></span></a></li>-->   
                </ul>
            </div>
            <!-- End Topbar -->

            <!-- Toggle get grouped for better mobile display -->
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="fa fa-bars"></span>
            </button>
            <!-- End Toggle -->
        </div><!--/end container-->

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse menu-xs navbar-responsive-collapse" >
            <div class="container">
                <ul class="nav navbar-nav " style="font-size: 10px;">
                    <li class="page-scroll home">
                        <a href="<?php echo $this->url('sanalfabrika', array('action' => 'index','lang'=> $this->langCode));
                            ?>#body"><?php echo $this->translate('9') ?></a>
                    </li>
                    <li class="page-scroll">
                        <a href="<?php echo $this->url('sanalfabrika', array('action' => 'index','lang'=> $this->langCode));
                            ?>#about"><?php echo $this->translate('229') ?></a>
                    </li>
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                            <?php echo $this->translate('230') ?>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="page-scroll"><a href="<?php echo $this->url('sanalfabrika', array('action' => 'index','lang'=> $this->langCode));
                            ?>#ostimServices">
                                    <?php echo $this->translate('15') ?></a>
                            </li>
                        </ul>
                    </li>
                    <li class="page-scroll">
                        <a href="<?php echo $this->url('sanalfabrika', array('action' => 'index','lang'=> $this->langCode));
                            ?>#news"><?php echo $this->translate('231') ?></a>
                    </li>
                    <li class="page-scroll">
                        <a href="<?php echo $this->url('sanalfabrika', array('action' => 'index','lang'=> $this->langCode));
                            ?>#contact"><?php echo $this->translate('232') ?></a>
                    </li>
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                            <?php echo $this->translate('0') ?>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="page-scroll">
                                <a href="<?php echo $this->url('sanalfabrika', array('action' => 'clientspage', 'lang' => $this->langCode)); ?>">
                                    <?php echo $this->translate('345') ?>
                                </a>
                            </li>
                            <li class="page-scroll">
                                <a href="<?php echo $this->url('sanalfabrika', array('action' => 'sfmachines', 'lang' => $this->langCode)); ?>">
                                    <?php echo $this->translate('446') ?>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div><!--/end container-->
        </div><!--/navbar-collapse-->
    </div>
    <!--=== End Header ===-->


    <!--=== Breadcrumbs ===-->
    <div class="breadcrumbs">
        <!--<div style='background: #FAF8F0;' class="container">--> 
        <div style='background: #E0EDDF;' class="container">
            <h1 id="header_company_name"  class="pull-left"><i class="fa fa-user"></i><?php echo $this->translate('Company Name') ?></h1>
            <ul class="pull-right breadcrumb">                        
                <?php $selectedCompanyNpk = $this->selectedCompanyNpk; ?>
                <li>
                    <a href="<?php echo $this->url('sanalfabrika', array('action' => 'index', 'lang' => $this->langcode));
                ?>">
                           <?php echo $this->translate('9') ?>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('sanalfabrika', array('action' => 'clientspage', 'lang' => $this->langcode));
                           ?>">
                           <?php echo $this->translate('345') ?>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('sanalfabrika', array('action' => 'companyprofile', 'lang' => $this->langcode ,'selectedCompanyShN' => $selectedCompanyShN, 'selectedCompanyNpk' => $selectedCompanyNpk));
                           ?>">
                           <?php echo $this->translate('258') ?>
                    </a>
                </li>
                <li class="active"><?php echo $this->translate('300') ?></li>
            </ul>
        </div>
    </div><!--/breadcrumbs-->
    <!--=== End Breadcrumbs ===-->


    <!--=== Profile ===-->
    <div class="container content profile" style="padding-top:0px;">
        <div class="row">
            <!--Left Sidebar-->
            <div class="col-md-3 md-margin-bottom-40">
                <img class="img-responsive profile-img margin-bottom-20" id="profileLogosrc"
                     src="" alt="" style="box-shadow: 0 0 30px #7c8082;">    

                <ul class="list-group sidebar-nav-v1 margin-bottom-40" id="sidebar-nav-1"></ul>
                <?php
//                if ($this->test_helper($this->firmaOwnerAllowance) == 'allowed') {
//                    echo '<ul class="list-group sidebar-nav-v1 margin-bottom-40" id="sidebar-nav-1">
//                </ul>';
//                } else {
//                    echo 'sorry';
//                }
//                
                ?>


                <div class="panel-heading-v2 overflow-h">
                    <h2 class="heading-xs pull-left">
                        <i class="fa fa-bar-chart-o"></i> 
                        <?php echo $this->translate('364') ?>
                    </h2>
                    <!--<a href="#"><i class="fa fa-cog pull-right"></i></a>-->
                </div>
                <h3 class="heading-xs">
                    <?php echo $this->translate('365') ?>
                    <span class="pull-right">92%</span>
                </h3>
                <div class="progress progress-u progress-xxs">
                    <div style="width: 92%" aria-valuemax="100" 
                         aria-valuemin="0" aria-valuenow="92" 
                         role="progressbar" class="progress-bar progress-bar-u">
                    </div>
                </div>
                <h3 class="heading-xs">
                    <?php echo $this->translate('366') ?>
                    <span class="pull-right">85%</span>
                </h3>
                <div class="progress progress-u progress-xxs">
                    <div style="width: 85%" aria-valuemax="100" 
                         aria-valuemin="0" aria-valuenow="85" 
                         role="progressbar" class="progress-bar progress-bar-blue">
                    </div>
                </div>
                <h3 class="heading-xs"> <?php echo $this->translate('367') ?>
                    <span class="pull-right">64%</span>
                </h3>
                <div class="progress progress-u progress-xxs margin-bottom-40">
                    <div style="width: 64%" aria-valuemax="100" 
                         aria-valuemin="0" aria-valuenow="64" 
                         role="progressbar" class="progress-bar progress-bar-dark">
                    </div>
                </div>

                <!-- Exchange Rates Script - EXCHANGERATEWIDGET.COM -->
                <div style="width:auto; border:0px solid #55A516; text-align:left;">
                    <div style="text-align:left;background-color:#717984;width:100%;
                         border-bottom:0px;height:30px; font-size:12px;
                         font-weight:bold;padding:5px 0px;">
                        <span style="margin-left:2px;background-image:url(//www.exchangeratewidget.com/flag.png); 
                              background-position: 0 -1232px; width:100%; height:15px; 
                              background-repeat:no-repeat;padding-left:5px;">
                            <a href="https://www.exchangeratewidget.com/" 
                               style="color:#FFFFFF; text-decoration:none;padding-left:22px;">
                                   <?php echo $this->translate('368') ?>
                            </a>
                        </span>
                    </div>
                    <script type="text/javascript" 
                            src="//www.exchangeratewidget.com/converter.php?l=en&f=TRY&t=EUR,USD,GBP,JPY,CHF,CAD,AUD,CNY,ZAR,RUB,BRL,HKD,&a=1&d=F0F0F0&n=FFFFFF&o=000000&v=5">
                    </script>
                </div>
                <!-- End of Exchange Rates Script -->

                <!--Notification-->
                <div class="box box-relative"  id="notificationContainer"  
                     data-bind=""
                     attr-notification="<?php echo $this->translate('20') ?>"
                     
                     >    
                <div class="panel-heading-v2 overflow-h " style="margin-top: 20px">
                    <h2 class="heading-xs pull-left"><i class="fa fa-bell-o"></i> 
                        <?php echo $this->translate('20') ?></h2>
                    <a href="#"><i class="fa fa-cog pull-right"></i></a>
                </div>
                <div class="margin-bottom-20 "  >
                    <ul class="list-unstyled mCustomScrollbar margin-bottom-20 box" 
                        data-mcs-theme="minimal-dark" id="notificationWidget"> 
                        <li class="notification">
                            <i class="icon-custom icon-sm rounded-x 
                               icon-bg-red icon-line icon-envelope"></i>
                            <div class="overflow-h">
                                <span><strong>Muhsin Teber</strong> <?php echo $this->translate('112') ?> <?php echo $this->translate('470') ?></span>
                                <small>2 <?php echo $this->translate('369') ?> <?php echo $this->translate('370') ?></small>
                            </div>    
                        </li>
                        <li class="notification">
                            <img class="rounded-x" 
                                 src="<?php echo $this->basePath('onyuz/standard/assets/img/women-icon.png') ?>" 
                                 alt="">
                            <div class="overflow-h">
                                <span><strong>Sedat Çelikdoğan</strong> <?php echo $this->translate('381') ?></span>
                                <small><?php echo $this->translate('297') ?> 18:25 </small>
                            </div>    
                        </li>
                        <li class="notification">
                            <i class="icon-custom icon-sm rounded-x icon-bg-yellow icon-line fa fa-bolt"></i>
                            <div class="overflow-h">
                                <span><strong>Adem Başarır</strong> <?php echo $this->translate('374') ?></span>
                                <small><?php echo $this->translate('298') ?> 13:07</small>
                            </div>    
                        </li>
                        <li class="notification">
                            <img class="rounded-x" 
                                 src="<?php echo $this->basePath('onyuz/standard/assets/img/men-icon.png') ?>" alt="">
                            <div class="overflow-h">
                                <span><strong>OSSA</strong> <?php echo $this->translate('376') ?></span>
                                <small>2 <?php echo $this->translate('375') ?> <?php echo $this->translate('370') ?> 12:09</small>
                            </div>    
                        </li>
                        <li class="notification">
                            <i class="icon-custom icon-sm rounded-x icon-bg-blue icon-line fa fa-comments"></i>
                            <div class="overflow-h">
                                <span><strong>Burhan Yetiş</strong> <?php echo $this->translate('377') ?></span>
                                <small>2 <?php echo $this->translate('375') ?> <?php echo $this->translate('370') ?> 09:34</small>
                            </div>    
                        </li>
                        <li class="notification">
                            <img class="rounded-x" 
                                 src="<?php echo $this->basePath('onyuz/standard/assets/img/women-icon.png') ?>" alt="">
                            <div class="overflow-h">
                                <span><strong>Orhan Aydın</strong> <?php echo $this->translate('372') ?></span>
                                <small>3 <?php echo $this->translate('375') ?> <?php echo $this->translate('370') ?> 14:28</small>  
                            </div>      
                        </li>
                    </ul>    
                </div>
                </div>                
                <!--/notifications -->
            </div>
            <!--End Left Sidebar-->


            <!-- Profile Content -->            
            <div class="col-md-9">
                <div class='row'>
                    <div class="panel panel-default">
                        <div class="panel-heading" style='background-color:#487f6d; color: #ffffff'>
                            <h4 class="panel-title accordion-toggle" data-toggle="collapse" data-parent="#accordion-1" href="#collapse-One">
                                <?php echo $this->translate('301') ?>
                            </h4>
                        </div>
                        <div id="collapse-One" class="panel-collapse collapse in">
                            <div class="panel-body" id='sample_header'>
                            </div>
                        </div>
                    </div>
                </div>

                <div class='row'>
                    <div class="panel panel-dark-blue">
                        <div class="panel-heading" style='background: #4765a0;color:#ffffff'>
                            <h3 class="panel-title">
                                <i class="fa fa-tasks"></i>
                                <?php echo $this->translate('302') ?>
                            </h3>
                        </div>
                        <div class="panel-body">
                            <?php echo $this->translate('303') ?>
                        </div>
                    </div>                    
                </div>

                <div class="row">
                    <div class="panel panel-purple">
                        <div class="panel-heading" style="background-color: #9b6bcc; color:#ffffff">
                            <h3 class="panel-title"><i class="fa fa-tasks"></i> 
                                <?php echo $this->translate('305') ?>
                            </h3>
                        </div>
                        <div class="panel-body">
                            <table id="product_table" 
                                   class="table table-hover table-striped table-condensed" 
                                   cellspacing="0" style="font-size: 12px">
                            </table>
                        </div>
                    </div>
                </div>


                <div class="row">
                    <div id='product_details_DIV' lastIndex='' style='visibility:hidden; display:none'> 
                    </div>
                </div>


                <div class="row">
                    <h2><?php echo $this->translate('304') ?></h2>
                    <p><?php
                        echo $this->translate('476')
                        ?></p>

                    <div class="row margin-bottom-60">
                        <!-- Vimeo Video -->
                        <div class="col-md-6">
                            <div class="responsive-video md-margin-bottom-40">
                                <iframe width="100%" src="https://www.youtube.com/embed/QsA0RZ7dXKk" 
                                        frameborder="0" allowfullscreen></iframe>
                            </div>
                        </div>
                        <!-- End Vimeo Video -->

                        <!-- Youtube Video -->
                        <div class="col-md-6">
                            <div class="responsive-video">
                                <iframe width="100%" src="https://www.youtube.com/embed/Sm6sPdpAFDY" 
                                        frameborder="0" allowfullscreen></iframe>
                            </div>
                        </div>
                        <!-- End Youtube Video -->
                    </div>
                    <!-- End Video Blocks -->
                </div>
            </div>
        </div>
    </div>
</div>  
<!--=== End Profile ===-->

    <!--=== Footer Version 1 ===-->
    <div class="footer-v1">
        <div class="footer">
            <div class="container">
                <div class="row">
                    <!-- About -->
                    <div class="col-md-3 md-margin-bottom-40">
                        <a href="<?php echo $this->url('sanalfabrika', array('action' => 'index', 'lang' => $this->langcode)); ?>"><img id="logo-footer" class="footer-logo" 
                                                    src="<?php echo $this->basePath('onyuz/standard/assets/img/logo2-default.png') ?>" 
                                                    alt=""></a>
                        <p><?php echo $this->translate('264')?></p>
                    </div><!--/col-md-3-->
                    <!-- End About -->

                    <!-- Latest -->
                    <div class="col-md-3 md-margin-bottom-40">
                        <div class="posts">
                            <div class="headline"><h2><?php echo $this->translate('261') ?></h2></div>
                            <ul class="list-unstyled latest-list">
                                <li>
                                    <a href="#"><?php echo $this->translate('265') ?></a>
                                    <small><?php echo $this->translate('286') ?> 8, 2016</small>
                                </li>
                                <li>
                                    <a href="#"><?php echo $this->translate('266') ?></a>
                                    <small><?php echo $this->translate('285') ?> 23, 2016</small>
                                </li>
                                <li>
                                    <a href="#"><?php echo $this->translate('267') ?></a>
                                    <small><?php echo $this->translate('296') ?> 15, 2016</small>
                                </li>
                            </ul>
                        </div>
                    </div><!--/col-md-3-->  
                    <!-- End Latest --> 

                    <!-- Link List -->
                    <div class="col-md-3 md-margin-bottom-40">
                        <div class="headline"><h2><?php echo $this->translate('262') ?></h2></div>
                        <ul class="list-unstyled link-list">
                            <li><a href="http://www.ostim.org.tr/"><?php echo $this->translate('268') ?></a><i class="fa fa-angle-right"></i></li>
                            <li><a href="http://www.sanayi.gov.tr/"><?php echo $this->translate('269') ?></a><i class="fa fa-angle-right"></i></li>
                            <li><a href="https://www.tubitak.gov.tr/"><?php echo $this->translate('270') ?></a><i class="fa fa-angle-right"></i></li>
                            <li><a href="http://www.kosgeb.gov.tr/"><?php echo $this->translate('271') ?></a><i class="fa fa-angle-right"></i></li>
                            <!--<li><a href="#"><?php echo $this->translate('') ?></a><i class="fa fa-angle-right"></i></li>-->
                        </ul>
                    </div><!--/col-md-3-->
                    <!-- End Link List -->                    

                    <!-- Address -->
                    <div class="col-md-3 map-img md-margin-bottom-40">
                        <div class="headline"><h2><?php echo $this->translate('110') ?></h2></div>                         
                        <address class="md-margin-bottom-40">
                            100. Yıl Bulvarı No: 101/A <br />
                            OSTIM, Ankara <br />
                            Turkey <br />
                            <?php echo $this->translate('147') ?> :  +90 312 385 50 90 <br />
                            <?php echo $this->translate('148') ?>:    +90 312 354 58 98 <br />
                            <?php echo $this->translate('112') ?>: <a href="mailto:info@ostim.com.tr" class="">info@ostim.com.tr</a>
                        </address>
                    </div><!--/col-md-3-->
                    <!-- End Address -->
                </div>
            </div> 
        </div><!--/footer-->

        <div class="copyright">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">                     
                        <p>
                            2016 &copy; <?php echo $this->translate('274') ?>
                            <a href="#"><?php echo $this->translate('273') ?></a> | <a href="#"><?php echo $this->translate('272') ?></a>
                        </p>
                    </div>

                    <!-- Social Links -->
                    <div class="col-md-6">
                        <ul class="footer-socials list-inline">
                            <li>
                                <a href="https://www.facebook.com/OstimOSB/" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Facebook">
                                    <i class="fa fa-facebook"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Skype">
                                    <i class="fa fa-skype"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://plus.google.com/+OST%C4%B0MOSB1967" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Google Plus">
                                    <i class="fa fa-google-plus"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://www.linkedin.com/in/ostim-osb-2b94b847" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Linkedin">
                                    <i class="fa fa-linkedin"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://www.instagram.com/ostimosb/" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Instagram">
                                    <i class="fa fa-instagram"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://twitter.com/ostimosb" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Twitter">
                                    <i class="fa fa-twitter"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Dribbble">
                                    <i class="fa fa-dribbble"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <!-- End Social Links -->
                </div>
            </div> 
        </div><!--/copyright-->
    </div>    
    <!--=== End Footer Version 1 ===-->
</div><!--/wrapper-->