<!DOCTYPE html>
<input id="requestUriRegulated" type="hidden"  value="<?php echo $this->requestUriRegulated; ?>"></input>
<input id="langCode" type="hidden"  value="<?php echo $this->langCode; ?>"></input>
<input id="pk" type="hidden"  value="<?php echo $this->publicKey; ?>"></input>
<input id="selectedCompanyNpk" type="hidden"  value="<?php echo $this->selectedCompanyNpk; ?>"></input>


<!--=== Style Switcher ===-->    
<i class="style-switcher-btn fa fa-cogs hidden-xs"></i>
<div class="style-switcher animated fadeInRight">
    <div class="style-swticher-header">
        <div class="style-switcher-heading">Style Switcher</div>            
        <div class="theme-close"><i class="icon-close"></i></div>
    </div>

    <div class="style-swticher-body">
        <!-- Theme Colors -->
        <div class="style-switcher-heading">Theme Colors</div>
        <ul class="list-unstyled">
            <li class="theme-default theme-active" data-style="default" data-header="light"></li>
            <li class="theme-blue" data-style="blue" data-header="light"></li>
            <li class="theme-orange" data-style="orange" data-header="light"></li>
            <li class="theme-red" data-style="red" data-header="light"></li>
            <li class="theme-light" data-style="light" data-header="light"></li>
            <li class="theme-purple last" data-style="purple" data-header="light"></li>
            <li class="theme-aqua" data-style="aqua" data-header="light"></li>
            <li class="theme-brown" data-style="brown" data-header="light"></li>
            <li class="theme-dark-blue" data-style="dark-blue" data-header="light"></li>
            <li class="theme-light-green" data-style="light-green" data-header="light"></li>
            <li class="theme-dark-red" data-style="dark-red" data-header="light"></li>
            <li class="theme-teal last" data-style="teal" data-header="light"></li>
        </ul>

        <!-- Theme Skins -->
        <div class="style-switcher-heading">Theme Skins</div>
        <div class="row no-col-space margin-bottom-20 skins-section">
            <div class="col-xs-6">
                <button data-skins="default" class="btn-u btn-u-xs btn-u-dark btn-block active-switcher-btn handle-skins-btn">Light</button>
            </div>
            <div class="col-xs-6">
                <button data-skins="dark" class="btn-u btn-u-xs btn-u-dark btn-block skins-btn">Dark</button>
            </div>
        </div>            

        <hr>

        <!-- Layout Styles -->
        <div class="style-switcher-heading">Layout Styles</div>
        <div class="row no-col-space margin-bottom-20">
            <div class="col-xs-6">
                <a href="javascript:void(0);" class="btn-u btn-u-xs btn-u-dark btn-block active-switcher-btn wide-layout-btn">Wide</a>                
            </div>
            <div class="col-xs-6">
                <a href="javascript:void(0);" class="btn-u btn-u-xs btn-u-dark btn-block boxed-layout-btn">Boxed</a>                
            </div>
        </div>            

        <hr>

        <!-- Theme Type -->
        <div class="style-switcher-heading">Theme Types and Versions</div>
        <div class="row no-col-space margin-bottom-10">
            <div class="col-xs-6">
                <a href="Shop-UI/index.html" class="btn-u btn-u-xs btn-u-dark btn-block">Shop UI <small class="dp-block">Template</small></a>
            </div>
            <div class="col-xs-6">
                <a href="One-Page/index.html" class="btn-u btn-u-xs btn-u-dark btn-block">One Page <small class="dp-block">Template</small></a>
            </div>
        </div>           

        <div class="row no-col-space">
            <div class="col-xs-6">
                <a href="Blog/index.html" class="btn-u btn-u-xs btn-u-dark btn-block">Blog <small class="dp-block">Template</small></a>
            </div>
            <div class="col-xs-6">
                <a href="RTL/index.html" class="btn-u btn-u-xs btn-u-dark btn-block">RTL <small class="dp-block">Version</small></a>
            </div>
        </div>           
    </div>
</div><!--/style-switcher-->
<!--=== End Style Switcher ===-->    

<div class="wrapper">
    <!--=== Header ===-->    
    <div class="header">
        <div class="container">
            <!-- Logo -->
            <a class="logo" href="index.html">
                <img src="<?php echo $this->basePath('onyuz/standard/assets/img/logo1-default.png') ?>" alt="Logo">
            </a>
            <!-- End Logo -->

            <!-- Topbar -->
            <div class="topbar">
                <ul style="background: #ddd;
                    padding: 10px;" class="loginbar pull-right">
                    <li class="hoverSelector">
                        <a><?php echo $this->translate('Languages') ?> </a>
                        <i class="fa fa-globe"></i>
                        <ul id='topLanguageBar' class="languages hoverSelectorBlock">                                    
                        </ul>
                    </li>
                    <li class="topbar-devider"></li>   
                    <li><a href="page_faq.html"><?php echo $this->translate('Help') ?></a></li>  
                    <li class="topbar-devider"></li>   
                    <li><a href="<?php echo $this->url('login', array('action' => 'logout')); ?>"><?php echo $this->translate('Log out') ?></a></li>   
                </ul>
            </div>
            <!-- End Topbar -->

            <!-- Toggle get grouped for better mobile display -->
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="fa fa-bars"></span>
            </button>
            <!-- End Toggle -->
        </div><!--/end container-->

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse menu-xs navbar-responsive-collapse" >
            <div class="container">
                <ul class="nav navbar-nav " style="font-size: 10px;">
                    <li class="page-scroll home">
                        <a href="#body"><?php echo $this->translate('Home') ?></a>
                    </li>
                    <li class="page-scroll">
                        <a href="#about"><?php echo $this->translate('About Us') ?></a>
                    </li>
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                            <?php echo $this->translate('Services') ?>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="page-scroll"><a href="#body">
                                    <?php echo $this->translate('OSTIM Services') ?></a>
                            </li>
                        </ul>
                    </li>
                    <li class="page-scroll">
                        <a href="#news"><?php echo $this->translate('News') ?></a>
                    </li>
                    <li class="page-scroll">
                        <a href="#contact"><?php echo $this->translate('Contacts') ?></a>
                    </li>
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                            <?php echo $this->translate('Submenus') ?>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="page-scroll">
                                <a href="#body"><?php echo $this->translate('Home') ?></a>
                            </li>
                            <li class="page-scroll">
                                <a href="../index-2.html"><?php echo $this->translate('Main') ?></a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div><!--/end container-->
        </div><!--/navbar-collapse-->
    </div>
    <!--=== End Header ===-->


    <!--=== Breadcrumbs ===-->
    <div class="breadcrumbs">
        <!--<div style='background: #FAF8F0;' class="container">--> 
        <div style='background: #E0EDDF;' class="container">
            <h1 id="header_company_name" class="pull-left"><i class="fa fa-user"></i><?php echo $this->translate('Company Name') ?></h1>
            <ul class="pull-right breadcrumb">                        
                <li>
                    <a href="<?php echo $this->url('sanalfabrika', array('action' => 'index'));
                            ?>">
                           <?php echo $this->translate('Home') ?>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('sanalfabrika', array('action' => 'clientspage'));
                           ?>">
                           <?php echo $this->translate('Clients Page') ?>
                    </a>
                </li>
                <li class="active"><?php echo $this->translate('Company Profile') ?></li>
            </ul>
        </div>
    </div><!--/breadcrumbs-->
    <!--=== End Breadcrumbs ===-->


    <!--=== Profile ===-->
    <div class="container content profile">
        <div class="row">
            <!--Left Sidebar-->
            <div class="col-md-3 md-margin-bottom-40">
                <img class="img-responsive profile-img margin-bottom-20" id="profileLogosrc"
                     src="" alt="">

                <ul class="list-group sidebar-nav-v1 margin-bottom-40" id="sidebar-nav-1">
                </ul>     

                <div class="panel-heading-v2 overflow-h">
                    <h2 class="heading-xs pull-left">
                        <i class="fa fa-bar-chart-o"></i> 
                        <?php echo $this->translate('Task Progress') ?>
                    </h2>
                    <a href="#"><i class="fa fa-cog pull-right"></i></a>
                </div>
                <h3 class="heading-xs">
                    <?php echo $this->translate('Web Design') ?> 
                    <span class="pull-right">92%</span>
                </h3>
                <div class="progress progress-u progress-xxs">
                    <div style="width: 92%" aria-valuemax="100" 
                         aria-valuemin="0" aria-valuenow="92" 
                         role="progressbar" class="progress-bar progress-bar-u">
                    </div>
                </div>
                <h3 class="heading-xs">
                    <?php echo $this->translate('Unify Project') ?> 
                    <span class="pull-right">85%</span>
                </h3>
                <div class="progress progress-u progress-xxs">
                    <div style="width: 85%" aria-valuemax="100" 
                         aria-valuemin="0" aria-valuenow="85" 
                         role="progressbar" class="progress-bar progress-bar-blue">
                    </div>
                </div>
                <h3 class="heading-xs"><?php echo $this->translate('Sony Corporation') ?>
                    <span class="pull-right">64%</span>
                </h3>
                <div class="progress progress-u progress-xxs margin-bottom-40">
                    <div style="width: 64%" aria-valuemax="100" 
                         aria-valuemin="0" aria-valuenow="64" 
                         role="progressbar" class="progress-bar progress-bar-dark">
                    </div>
                </div>

                <hr>

                <!--Notification-->
                <div class="panel-heading-v2 overflow-h">
                    <h2 class="heading-xs pull-left"><i class="fa fa-bell-o"></i> 
                        <?php echo $this->translate('Notification') ?></h2>
                    <a href="#"><i class="fa fa-cog pull-right"></i></a>
                </div>
                <div class="margin-bottom-20">
                    <ul class="list-unstyled mCustomScrollbar margin-bottom-20" 
                        data-mcs-theme="minimal-dark">
                        <li class="notification">
                            <i class="icon-custom icon-sm rounded-x 
                               icon-bg-red icon-line icon-envelope"></i>
                            <div class="overflow-h">
                                <span><strong>Albert Heller</strong> has sent you email.</span>
                                <small>Two minutes ago</small>
                            </div>    
                        </li>
                        <li class="notification">
                            <img class="rounded-x" 
                                 src="<?php echo $this->basePath('onyuz/assets/img/testimonials/img6.jpg') ?>" 
                                 alt="">
                            <div class="overflow-h">
                                <span><strong>Taylor Lee</strong> started following you.</span>
                                <small>Today 18:25 pm</small>
                            </div>    
                        </li>
                        <li class="notification">
                            <i class="icon-custom icon-sm rounded-x icon-bg-yellow icon-line fa fa-bolt"></i>
                            <div class="overflow-h">
                                <span><strong>Natasha Kolnikova</strong> accepted your invitation.</span>
                                <small>Yesterday 1:07 pm</small>
                            </div>    
                        </li>
                        <li class="notification">
                            <img class="rounded-x" 
                                 src="<?php echo $this->basePath('onyuz/assets/img/testimonials/img1.jpg') ?>" alt="">
                            <div class="overflow-h">
                                <span><strong>Mikel Andrews</strong> commented on your Timeline.</span>
                                <small>23/12 11:01 am</small>
                            </div>    
                        </li>
                        <li class="notification">
                            <i class="icon-custom icon-sm rounded-x icon-bg-blue icon-line fa fa-comments"></i>
                            <div class="overflow-h">
                                <span><strong>Bruno Js.</strong> added you to group chating.</span>
                                <small>Yesterday 1:07 pm</small>
                            </div>    
                        </li>
                        <li class="notification">
                            <img class="rounded-x" 
                                 src="<?php echo $this->basePath('onyuz/assets/img/testimonials/img6.jpg') ?>" alt="">
                            <div class="overflow-h">
                                <span><strong>Taylor Lee</strong> changed profile picture.</span>
                                <small>23/12 15:15 pm</small>
                            </div>    
                        </li>
                    </ul>    
                </div>
            </div>
            <!--End Left Sidebar-->

            <!-- Counter header start -->
            <div class="col-md-9" style="padding-bottom: 20px">
                <!--<div class="parallax-counter-v4 parallaxBg">-->
                <!--Service Block v3-->
                <div class="row margin-bottom-10">
                    <div class="col-sm-6 sm-margin-bottom-20">
                        <div class="service-block-v3 service-block-aviation">
                            <i class="icon-plane"></i>
                            <span class="service-heading">
                                <?php echo $this->translate('Submitted Aviation Projects') ?>
                            </span>
                            <span class="counter">358</span>

                            <div class="clearfix margin-bottom-10"></div>

                            <div class="row margin-bottom-20">
                                <div class="col-xs-6 service-in">
                                    <small><?php echo $this->translate('Last Week') ?></small>
                                    <h4 class="counter">25</h4>
                                </div>
                                <div class="col-xs-6 text-right service-in">
                                    <small><?php echo $this->translate('Last Month') ?></small>
                                    <h4 class="counter">114</h4>
                                </div>
                            </div>
                            <div class="statistics">
                                <h3 class="heading-xs"><?php echo $this->translate('Statistics in Progress Bar') ?><span class="pull-right">67%</span></h3>
                                <div class="progress progress-u progress-xxs">
                                    <div style="width: 67%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="67" role="progressbar" class="progress-bar progress-bar-light">
                                    </div>
                                </div>
                                <small>11% less <strong><?php echo $this->translate('than last month') ?></strong></small>
                            </div>            
                        </div>
                    </div>


                    <div class="col-sm-6">
                        <div class="service-block-v3 service-block-renewable">
                            <i class="icon-energy"></i>
                            <span class="service-heading">
                                <?php echo $this->translate('Submitted Renewable Energy Projects') ?>
                            </span>
                            <span class="counter">324,056</span>

                            <div class="clearfix margin-bottom-10"></div>

                            <div class="row margin-bottom-20">
                                <div class="col-xs-6 service-in">
                                    <small><?php echo $this->translate('Last Week') ?></small>
                                    <h4 class="counter">26,904</h4>
                                </div>
                                <div class="col-xs-6 text-right service-in">
                                    <small><?php echo $this->translate('Last Month') ?></small>
                                    <h4 class="counter">124,766</h4>
                                </div>
                            </div>
                            <div class="statistics">
                                <h3 class="heading-xs"><?php echo $this->translate('Statistics in Progress Bar') ?><span class="pull-right">89%</span></h3>
                                <div class="progress progress-u progress-xxs">
                                    <div style="width: 89%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="89" role="progressbar" class="progress-bar progress-bar-light">
                                    </div>
                                </div>
                                <small>15% <?php echo $this->translate('higher') ?> <strong><?php echo $this->translate('than last month') ?></strong></small>
                            </div>            
                        </div>
                    </div>
                </div><!--/end row-->
                <!--End Service Block v3-->                    
                <!--</div>-->
            </div>


            <!-- Counter header ends -->

            <!-- Profile Content -->            
            <div class="col-md-9">
                <div class="profile-body">
                    <div class="block-description">
                        <div class="container">
                            <div class="title-box-v2 col-md-8" id="companyAddressPH">
                            </div> 
                            <div class="row">
                                <div class="col-md-8">
                                    <!-- Left Inner -->
                                    <div class="left-inner">
                                        <img id="logosrc" src="" style="width: 20%; height: 20%"  alt="">                                        
                                        <h4 id="logoName"></h4>
                                        <a href="#"><i class="position-top fa fa-print"></i></a>

                                        <div class="overflow-h">
                                            <p class="hex" id="companyInfoPH"><?php echo $this->translate('Turkey') ?>, 200 <?php echo $this->translate('Employees') ?></p>
                                            <ul class="list-inline star-vote">
                                                <li><i class="color-green fa fa-star"></i></li>
                                                <li><i class="color-green fa fa-star"></i></li>
                                                <li><i class="color-green fa fa-star"></i></li>
                                                <li><i class="color-green fa fa-star-half-o"></i></li>
                                                <li><i class="color-green fa fa-star-o"></i></li>
                                            </ul>                                            
                                            <span><a href="#">34 <?php echo $this->translate('reviews') ?></a></span>

                                        </div>
                                        <ul class="social-icons" id="socialMediaHP">
                                        </ul> 
                                    </div>
                                </div>
                            </div> 

                            <div class='row' style='margin-top: 20px; margin-bottom: 20px'>
                                <div class='col-md-8'>
                                    <div class="left-inner">
                                        <div class="process-v1 bg-color-light">
                                            <div class='row'>
                                                <div class="headline-center margin-bottom-60">
                                                    <h2><?php echo $this->translate('Company Capabilities') ?></h2>
                                                    <p><strong id='company_name_PH'></strong><br><?php echo $this->translate('is competitive in: ') ?></p>
                                                </div>
                                            </div>

                                            <div class='row'>  
                                                <ul class="list-inline row process-in process-border">
                                                    <li class="col-xs-3 sm-margin-bottom-50">
                                                        <div class="process-icon">
                                                            <i class="rounded-x dot-active"></i>
                                                        </div>
                                                        <div class="process-desc">
                                                            <h3>
                                                                <?php echo $this->translate('Precise Metal Cutting') ?>
                                                            </h3>
                                                        </div>
                                                    </li>
                                                    <li class="col-xs-3 sm-margin-bottom-50">
                                                        <div class="process-icon">
                                                            <i class="rounded-x dot-active"></i>
                                                        </div>
                                                        <div class="process-desc">
                                                            <h3>
                                                                <?php echo $this->translate('Plastic Injection') ?>
                                                            </h3>
                                                        </div>
                                                    </li>
                                                    <li class="col-xs-3 sm-margin-bottom-50">
                                                        <div class="process-icon">
                                                            <i class="rounded-x dot-active"></i>
                                                        </div>
                                                        <div class="process-desc">
                                                            <h3>
                                                                <?php echo $this->translate('Wire Cutting') ?>
                                                            </h3>
                                                        </div>
                                                    </li>
                                                    <li class="col-xs-3">
                                                        <div class="process-icon">
                                                            <i class="rounded-x dot-active"></i>
                                                        </div>
                                                        <div class="process-desc">
                                                            <h3>
                                                                <?php echo $this->translate('Electronic Circuits') ?>
                                                            </h3>
                                                        </div>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>                                        
                                    </div>                                    
                                </div>
                            </div>

                            <div id="company_performance_div" class="row" style='margin-top: 20px; margin-bottom: 20px'>
                                <div class="col-md-8">                                    
                                    <!-- Left Inner -->
                                    <div class="left-inner">
                                        <div class='row'>
                                            <div class="headline-center margin-bottom-60">
                                                <h2><?php echo $this->translate('Company Performance') ?></h2>
                                                <p><strong id='company_name_PH'></strong><br> <?php echo $this->translate('Last 12 months performance regarding last year') ?></p>
                                            </div>
                                        </div>
                                        <div class="progression">
                                            <span><?php echo $this->translate('Production Increase') ?></span>
                                            <div class="progress progress-u progress-xs">
                                                <div style="width: 88%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="88" role="progressbar" class="progress-bar progress-bar-u">
                                                </div>
                                            </div>

                                            <span><?php echo $this->translate('Employee Increase') ?></span>
                                            <div class="progress progress-u progress-xs">
                                                <div style="width: 76%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="76" role="progressbar" class="progress-bar progress-bar-u">
                                                </div>
                                            </div>

                                            <span><?php echo $this->translate('Energy Consumption') ?></span>
                                            <div class="progress progress-u progress-xs">
                                                <div style="width: 97%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="97" role="progressbar" class="progress-bar progress-bar-u">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row" style='margin-top: 20px; margin-bottom: 20px'>
                                <div class="col-md-8">                                    
                                    <!-- Left Inner -->
                                    <div class="left-inner">
                                        <div class="progression">
                                            <div class='row'>
                                                <div class="headline-center margin-bottom-60">
                                                    <h2><?php echo $this->translate('Company Brief Description') ?></h2>
                                                    <p><strong id='company_name_PH'></strong><br> <?php echo $this->translate('description') ?></p>
                                                </div>
                                            </div>
                                            <p id="briefDescPH">                                                
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row" style='margin-top: 20px; margin-bottom: 20px;'>
                                <div class="col-md-8">                                    
                                    <!-- Left Inner -->
                                    <div class="left-inner">
                                        <div class="progression">
                                            <div class="headline-center margin-bottom-60">
                                                <h2><?php echo $this->translate('References') ?></h2>
                                            </div>
                                        </div>
                                        <div class='content job-partners'>
                                            <ul class="list-inline our-clients" id="effect-2">
                                                <li>
                                                    <figure>
                                                        <img src="<?php echo $this->basePath('onyuz/standard/assets/img/clients2/ea-canada.png') ?>" alt="">
                                                        <div class="img-hover">
                                                            <h4>Ea Canada</h4>
                                                        </div>
                                                    </figure>
                                                </li> 
                                                <li>
                                                    <figure>
                                                        <img src="<?php echo $this->basePath('onyuz/standard/assets/img/clients2/inspiring.png') ?>" alt="">
                                                        <div class="img-hover">
                                                            <h4>Inspiring</h4>  
                                                        </div>
                                                    </figure>
                                                </li>    
                                                <li>
                                                    <figure>
                                                        <img src="<?php echo $this->basePath('onyuz/standard/assets/img/clients2/ucweb.png') ?>" alt="">  
                                                        <div class="img-hover">
                                                            <h4>UcWeb</h4>  
                                                        </div>
                                                    </figure>
                                                </li>  
                                                <li>
                                                    <figure>
                                                        <img src="<?php echo $this->basePath('onyuz/standard/assets/img/clients2/clarks.png') ?>" alt="">  
                                                        <div class="img-hover">
                                                            <h4>Clarks</h4>
                                                        </div>
                                                    </figure>
                                                </li>    
                                                <li>
                                                    <figure>
                                                        <img src="<?php echo $this->basePath('onyuz/standard/assets/img/clients2/corepreserves.png') ?>" alt="">  
                                                        <div class="img-hover">
                                                            <h4>Core Preserves</h4>
                                                        </div>
                                                    </figure>
                                                </li>    
                                                <li>
                                                    <figure>
                                                        <img src="<?php echo $this->basePath('onyuz/standard/assets/img/clients2/finals.png') ?>" alt="">  
                                                        <div class="img-hover">
                                                            <h4>USL Champions</h4>
                                                        </div>
                                                    </figure>
                                                </li>    
                                                <li>
                                                    <figure>
                                                        <img src="<?php echo $this->basePath('onyuz/standard/assets/img/clients2/getaround.png') ?>" alt="">  
                                                        <div class="img-hover">
                                                            <h4>GetAround</h4>
                                                        </div>
                                                    </figure>
                                                </li>
                                                <li>
                                                    <figure>
                                                        <img src="<?php echo $this->basePath('onyuz/standard/assets/img/clients2/baderbrau.png') ?>" alt="">  
                                                        <div class="img-hover">
                                                            <h4>Baderbrau</h4>
                                                        </div>
                                                    </figure>
                                                </li>      
                                                <li>
                                                    <figure>
                                                        <img src="<?php echo $this->basePath('onyuz/standard/assets/img/clients2/emirates.png') ?>" alt="">  
                                                        <div class="img-hover">
                                                            <h4>Emirates</h4>
                                                        </div>
                                                    </figure>
                                                </li>    
                                                <li>
                                                    <figure>
                                                        <img src="<?php echo $this->basePath('onyuz/standard/assets/img/clients2/fddw.png') ?>" alt="">  
                                                        <div class="img-hover">
                                                            <h4>Field Days</h4>
                                                        </div>
                                                    </figure>
                                                </li>    
                                                <li>
                                                    <figure>
                                                        <img src="<?php echo $this->basePath('onyuz/standard/assets/img/clients2/district-karaoke.png') ?>" alt="">  
                                                        <div class="img-hover">
                                                            <h4>District Karaoke</h4>
                                                        </div>
                                                    </figure>
                                                </li>        
                                                <li>
                                                    <figure>
                                                        <img src="<?php echo $this->basePath('onyuz/standard/assets/img/clients2/marianos.png') ?>" alt="">  
                                                        <div class="img-hover">
                                                            <h4>Mariano's</h4>
                                                        </div>
                                                    </figure>
                                                </li>    
                                                <li>
                                                    <figure>
                                                        <img src="<?php echo $this->basePath('onyuz/standard/assets/img/clients2/grifting-tree.png') ?>" alt="">  
                                                        <div class="img-hover">
                                                            <h4>The Grifting Tree</h4>
                                                        </div>
                                                    </figure>
                                                </li>    
                                                <li>
                                                    <figure>
                                                        <img src="<?php echo $this->basePath('onyuz/standard/assets/img/clients2/jaguar.png') ?>" alt="">  
                                                        <div class="img-hover">
                                                            <h4>Jaguar</h4>
                                                        </div>
                                                    </figure>
                                                </li>    
                                                <li>
                                                    <figure>
                                                        <img src="<?php echo $this->basePath('onyuz/standard/assets/img/clients2/hermes.png') ?>" alt="">  
                                                        <div class="img-hover">
                                                            <h4>Hermes</h4>
                                                        </div>
                                                    </figure>
                                                </li> 
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            <div id="customers_div" class="row" style='margin-top: 20px; margin-bottom: 20px;'>
                                <div class="col-md-8">                                    
                                    <!-- Left Inner -->
                                    <div class="left-inner">
                                        <div class="progression">
                                            <div class="headline-center margin-bottom-60">
                                                <h2><?php echo $this->translate('Customers') ?></h2>
                                            </div>
<!--                                            <ul class="list-unstyled" id="customersPH">
                                            </ul>-->
                                            <div class="bg-color-light">
                                                <div class="owl-clients-v1 owl-carousel owl-theme" style="opacity: 1; display: block;">
                                                    <div class="owl-wrapper-outer">
                                                        <div id="customersPH" class="owl-wrapper" style="width: 2412px; left: 0px; display: block; transition: all 800ms ease; transform: translate3d(-268px, 0px, 0px);">
                                                            <div class="owl-item" style="width: 134px;">
                                                                <div class="item">
                                                                    <img src="<?php echo $this->basePath('onyuz/standard/assets/img/clients4/1.png')?>" alt="">
                                                                </div>
                                                            </div>
                                                            <div class="owl-item" style="width: 134px;">
                                                                <div class="item">
                                                                    <img src="<?php echo $this->basePath('onyuz/standard/assets/img/clients4/2.png')?>" alt="">
                                                                </div>
                                                            </div>
                                                            <div class="owl-item" style="width: 134px;">
                                                                <div class="item">
                                                                    <img src="<?php echo $this->basePath('onyuz/standard/assets/img/clients4/3.png')?>" alt="">
                                                                </div>
                                                            </div>
                                                            <div class="owl-item" style="width: 134px;">
                                                                <div class="item">
                                                                    <img src="<?php echo $this->basePath('onyuz/standard/assets/img/clients4/4.png')?>" alt="">
                                                                </div>
                                                            </div>
                                                            <div class="owl-item" style="width: 134px;">
                                                                <div class="item">
                                                                    <img src="<?php echo $this->basePath('onyuz/standard/assets/img/clients4/5.png')?>" alt="">
                                                                </div>
                                                            </div>
                                                            <div class="owl-item" style="width: 134px;">
                                                                <div class="item">
                                                                    <img src="<?php echo $this->basePath('onyuz/standard/assets/img/clients4/6.png')?>" alt="">
                                                                </div>
                                                            </div>
                                                            <div class="owl-item" style="width: 134px;">
                                                                    <div class="item">
                                                                    <img src="<?php echo $this->basePath('onyuz/standard/assets/img/clients4/7.png')?>" alt="">
                                                                </div>
                                                            </div>
                                                            <div class="owl-item" style="width: 134px;">
                                                                <div class="item">
                                                                    <img src="<?php echo $this->basePath('onyuz/standard/assets/img/clients4/8.png')?>" alt="">
                                                                </div>
                                                            </div>
                                                            <div class="owl-item" style="width: 134px;">
                                                                <div class="item">
                                                                    <img src="<?php echo $this->basePath('onyuz/standard/assets/img/clients4/9.png')?>" alt="">
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="owl-controls clickable">
                                                        <div class="owl-pagination">
                                                            <div class="owl-page">
                                                                <span class="">
                                                                    
                                                                </span>
                                                            </div>
                                                            <div class="owl-page active">
                                                                <span class="">
                                                                    
                                                                </span>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                    </div>
                                    <!-- End Left Inner -->
                                </div>    
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Profile Content -->            
        </div>
    </div><!--/container-->    
    <!--=== End Profile ===-->

    <!--=== Footer Version 1 ===-->
    <div class="footer-v1">
        <div class="footer">
            <div class="container">
                <div class="row">
                    <!-- About -->
                    <div class="col-md-3 md-margin-bottom-40">
                        <a href="index-2.html"><img id="logo-footer" class="footer-logo" 
                                                    src="<?php echo $this->basePath('onyuz/standard/assets/img/logo2-default.png') ?>" 
                                                    alt=""></a>
                        <p><?php
                            echo $this->translate('A virtual enterprise (VE) is a temporary alliance of '
                                    . 'businesses that come together to share skills or core competencies and resources '
                                    . 'in order to better respond to business opportunities, and whose cooperation is '
                                    . 'supported by computer networks.')
                            ?></p>
                    </div><!--/col-md-3-->
                    <!-- End About -->

                    <!-- Latest -->
                    <div class="col-md-3 md-margin-bottom-40">
                        <div class="posts">
                            <div class="headline"><h2><?php echo $this->translate('Latest Posts') ?></h2></div>
                            <ul class="list-unstyled latest-list">
                                <li>
                                    <a href="#"><?php echo $this->translate('Latest News about OSTIM VE') ?></a>
                                    <small><?php echo $this->translate('February') ?> 8, 2016</small>
                                </li>
                                <li>
                                    <a href="#"><?php echo $this->translate('OSTIM Clusters News') ?></a>
                                    <small><?php echo $this->translate('January') ?> 23, 2016</small>
                                </li>
                                <li>
                                    <a href="#"><?php echo $this->translate('New Project Calls') ?></a>
                                    <small><?php echo $this->translate('December') ?> 15, 2016</small>
                                </li>
                            </ul>
                        </div>
                    </div><!--/col-md-3-->  
                    <!-- End Latest --> 

                    <!-- Link List -->
                    <div class="col-md-3 md-margin-bottom-40">
                        <div class="headline"><h2><?php echo $this->translate('Useful Links') ?></h2></div>
                        <ul class="list-unstyled link-list">
                            <li><a href="http://www.ostim.org.tr/"><?php echo $this->translate('Ostim Organized Industrial Zone') ?></a><i class="fa fa-angle-right"></i></li>
                            <li><a href="http://www.sanayi.gov.tr/"><?php echo $this->translate('Turkish Ministry of SIT') ?></a><i class="fa fa-angle-right"></i></li>
                            <li><a href="https://www.tubitak.gov.tr/"><?php echo $this->translate('TUBITAK') ?></a><i class="fa fa-angle-right"></i></li>
                            <li><a href="http://www.kosgeb.gov.tr/"><?php echo $this->translate('KOSGEB') ?></a><i class="fa fa-angle-right"></i></li>
                            <!--<li><a href="#"><?php echo $this->translate('') ?></a><i class="fa fa-angle-right"></i></li>-->
                        </ul>
                    </div><!--/col-md-3-->
                    <!-- End Link List -->                    

                    <!-- Address -->
                    <div class="col-md-3 map-img md-margin-bottom-40">
                        <div class="headline"><h2><?php echo $this->translate('Contact Us') ?></h2></div>                         
                        <address class="md-margin-bottom-40">
                            100. Yıl Bulvarı No: 101/A <br />
                            OSTIM, Ankara <br />
                            Turkey <br />
                            <?php echo $this->translate('Phone') ?> :  +90 312 385 50 90 <br />
                            <?php echo $this->translate('Fax') ?>:    +90 312 354 58 98 <br />
                            <?php echo $this->translate('Email') ?>: <a href="mailto:info@ostim.com.tr" class="">info@ostim.com.tr</a>
                        </address>
                    </div><!--/col-md-3-->
                    <!-- End Address -->
                </div>
            </div> 
        </div><!--/footer-->

        <div class="copyright">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">                     
                        <p>
                            2016 &copy; <?php echo $this->translate('All Rights Reserved.') ?>
                            <a href="#"><?php echo $this->translate('Privacy Policy') ?></a> | <a href="#"><?php echo $this->translate('Terms of Service') ?></a>
                        </p>
                    </div>

                    <!-- Social Links -->
                    <div class="col-md-6">
                        <ul class="footer-socials list-inline">
                            <li>
                                <a href="https://www.facebook.com/OstimOSB/" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Facebook">
                                    <i class="fa fa-facebook"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Skype">
                                    <i class="fa fa-skype"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://plus.google.com/+OST%C4%B0MOSB1967" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Google Plus">
                                    <i class="fa fa-google-plus"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://www.linkedin.com/in/ostim-osb-2b94b847" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Linkedin">
                                    <i class="fa fa-linkedin"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://www.instagram.com/ostimosb/" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Instagram">
                                    <i class="fa fa-instagram"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://twitter.com/ostimosb" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Twitter">
                                    <i class="fa fa-twitter"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Dribbble">
                                    <i class="fa fa-dribbble"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <!-- End Social Links -->
                </div>
            </div> 
        </div><!--/copyright-->
    </div>        
    <!--=== End Footer Version 1 ===-->
</div><!--/wrapper-->