

<!DOCTYPE html> 
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->  
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->  
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->  

    <input id="requestUriRegulated" type="hidden"  value="<?php echo $this->requestUriRegulated; ?>"></input>
    <input id="langCode" type="hidden"  value="<?php echo $this->langCode; ?>"></input> 
    <input id="pktemp" type="hidden" value=""></input>    
    <input id="controller" type="hidden"  value="<?php echo $this->layout()->controller; ?>"></input>
    <input id="module" type="hidden"  value="<?php echo $this->layout()->module; ?>"></input>
    <input id="lastInsertId" type="hidden"  value=""></input>
    <!--checks if first tab is completed and submitted successfully.-->
    <input id="checkGeneralForm" type="hidden" value="0"></input>
    <!--checks if second tab is completed and submitted successfully.-->
    <input id="checkAddressForm" type="hidden" value="0"></input>
    <!--checks if third tab is completed and submitted successfully.-->
    <input id="checkCommunicationForm" type="hidden" value="0"></input>
    <!--checks if forth tab is completed and submitted successfully.-->
    <input id="checkCompanyForm" type="hidden" value="0"></input>


    <body>
        <!--=== Style Switcher ===-->    
        <i class="style-switcher-btn fa fa-cogs hidden-xs"></i>
        <div class="style-switcher animated fadeInRight">
            <div class="style-swticher-header">
                <div class="style-switcher-heading"><?php echo $this->translate('Style Switcher') ?> </div>            
                <div class="theme-close"><i class="icon-close"></i></div>
            </div>

            <div class="style-swticher-body">
                <!-- Theme Colors -->
                <div class="style-switcher-heading"><?php echo $this->translate('Style Switcher') ?> Theme Colors</div>
                <ul class="list-unstyled">
                    <li class="theme-default theme-active" data-style="default" data-header="light"></li>
                    <li class="theme-blue" data-style="blue" data-header="light"></li>
                    <li class="theme-orange" data-style="orange" data-header="light"></li>
                    <li class="theme-red" data-style="red" data-header="light"></li>
                    <li class="theme-light" data-style="light" data-header="light"></li>
                    <li class="theme-purple last" data-style="purple" data-header="light"></li>
                    <li class="theme-aqua" data-style="aqua" data-header="light"></li>
                    <li class="theme-brown" data-style="brown" data-header="light"></li>
                    <li class="theme-dark-blue" data-style="dark-blue" data-header="light"></li>
                    <li class="theme-light-green" data-style="light-green" data-header="light"></li>
                    <li class="theme-dark-red" data-style="dark-red" data-header="light"></li>
                    <li class="theme-teal last" data-style="teal" data-header="light"></li>
                </ul>

                <!-- Theme Skins -->
                <div class="style-switcher-heading"><?php echo $this->translate('Theme Skins') ?> </div>
                <div class="row no-col-space margin-bottom-20 skins-section">
                    <div class="col-xs-6">
                        <button data-skins="default" 
                                class="btn-u btn-u-xs btn-u-dark btn-block active-switcher-btn handle-skins-btn">
                                    <?php echo $this->translate('Light') ?> 
                        </button>
                    </div>
                    <div class="col-xs-6">
                        <button data-skins="dark" 
                                class="btn-u btn-u-xs btn-u-dark btn-block skins-btn">
                                    <?php echo $this->translate('Dark') ?> 
                        </button>
                    </div>
                </div>            

                <hr>

                <!-- Layout Styles -->
                <div class="style-switcher-heading"><?php echo $this->translate('Layout Styles') ?> </div>
                <div class="row no-col-space margin-bottom-20">
                    <div class="col-xs-6">
                        <a href="javascript:void(0);" 
                           class="btn-u btn-u-xs btn-u-dark btn-block active-switcher-btn wide-layout-btn">
                               <?php echo $this->translate('Wide') ?>
                        </a>                
                    </div>
                    <div class="col-xs-6">
                        <a href="javascript:void(0);" 
                           class="btn-u btn-u-xs btn-u-dark btn-block boxed-layout-btn">
                               <?php echo $this->translate('Boxed') ?> 
                        </a>                
                    </div>
                </div>
                <hr>
                <!-- Theme Type -->
                <div class="style-switcher-heading">
                    <?php echo $this->translate('Theme Types and Versions') ?>
                </div>
                <div class="row no-col-space margin-bottom-10">
                    <div class="col-xs-6">
                        <a href="Shop-UI/index.html" 
                           class="btn-u btn-u-xs btn-u-dark btn-block">
                               <?php echo $this->translate('Shop UI') ?>  
                            <small class="dp-block">
                                <?php echo $this->translate('Template') ?> 
                            </small>
                        </a>
                    </div>
                    <div class="col-xs-6">
                        <a href="One-Page/index.html" 
                           class="btn-u btn-u-xs btn-u-dark btn-block">
                               <?php echo $this->translate('One Page') ?>  
                            <small class="dp-block">
                                <?php echo $this->translate('Template') ?> 
                            </small>
                        </a>
                    </div>
                </div>           

                <div class="row no-col-space">
                    <div class="col-xs-6">
                        <a href="Blog/index.html" 
                           class="btn-u btn-u-xs btn-u-dark btn-block">
                               <?php echo $this->translate('Blog') ?>  
                            <small class="dp-block">
                                <?php echo $this->translate('Template') ?> 
                            </small>
                        </a>
                    </div>
                    <div class="col-xs-6">
                        <a href="RTL/index.html" 
                           class="btn-u btn-u-xs btn-u-dark btn-block">
                               <?php echo $this->translate('RTL') ?>  
                            <small class="dp-block">
                                <?php echo $this->translate('Version') ?> 
                            </small>
                        </a>
                    </div>
                </div>           
            </div>
        </div><!--/style-switcher-->
        <!--=== End Style Switcher ===-->    
        <div class="row">
            <div class="wrapper">
                <!--=== Header ===-->    
                <div class="header">
                    <div class="container">
                        <!-- Logo -->
                        <a class="logo" href="index.phtml">
                            <img src="<?php echo $this->basePath('onyuz/standard/assets/img/logo1-default.png') ?>" alt="Logo">
                        </a>
                        <!-- End Logo -->

                        <!-- Topbar -->
                        <div class="topbar">
                            <ul class="loginbar pull-right">
                                <!--User topbar -->
                                <li class="hoverSelector" id="user_profile_link" style="visibility: hidden; display: none">
                                    <a style="cursor: pointer;">
                                        <img id="user_image_ph" style="max-height: 20px; margin-right: 10px" 
                                             class="rounded-2x" src="" alt="">                            
                                        <span id='user_name'></span>
                                    </a>
                                    <ul id='topUserBar' class="users hoverSelectorBlock">
                                        <div class='col-md-12'>
                                            <div class="col-sm-2"  style="margin-top: 20px">
                                                <img id="user_image_ph_hover" style="max-height: 60px; margin: 5px;" 
                                                     class="rounded-2x" src="" alt="">
                                                <!--<i id="icon_ph" style="font-size: 50px" class="icon-user"></i>-->
                                                <span id="icon_ph" style="font-size: 50px;vertical-align: middle" aria-hidden="true" class="fa fa-user"></span>
                                            </div>
                                            <div class="col-sm-10" style="margin-top: 20px">
                                                <span class="col-sm-6 user_top_text_header">
                                                    <?php echo $this->translate('111') ?>:
                                                </span>
                                                <span class="col-sm-6 user_top_text" id='user_name_hover'></span>                                        
                                                <span class="col-sm-6 user_top_text_header">
                                                    <?php echo $this->translate('596') ?>:
                                                </span>
                                                <span class="col-sm-6 user_top_text" id='user_reg_date'></span>
                                            </div>
                                        </div>
                                        <div class='col-md-12'>
                                            <span style ='text-align: center;vertical-align: middle; line-height: 40px;' 
                                                  class="col-sm-12 user_top_text_header">
                                                      <?php echo $this->translate('603') ?> 
                                            </span>
                                            <li>
                                                <a href=''>
                                                    <table>
                                                        <tr>
                                                            <td class="col-md-8 user_top_text_header">
                                                                <i class='fa fa-tags'></i><?php echo $this->translate('604') ?>
                                                            </td>
                                                            <td class="col-md-4">
                                                                <img id="membership_tag" style="max-height: 30px; margin: 5px;" 
                                                                     class="rounded-x" src="" alt="">
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </a>
                                            </li>
                                        </div>
                                        <div class='col-md-12'>
                                            <span style ='text-align: center;vertical-align: middle; line-height: 40px;' 
                                                  class="col-sm-12 user_top_text_header">
                                                      <?php echo $this->translate('597') ?> 
                                            </span>
                                        </div>
                                        <div class='col-md-12'>
                                            <li style ='text-align: center;vertical-align: middle; line-height: 40px;'>
                                                <a id="link_to_user_profile" href="">
                                                    <i class="fa fa-user" style='margin-right: 5px'></i><?php echo $this->translate('598') ?>
                                                </a>
                                            </li>
                                        </div>
                                        <!--                            <div class='col-md-12'>
                                                                        <li style ='text-align: center;vertical-align: middle; line-height: 40px;'>
                                                                            <a href="">
                                                                                <i class="fa fa-gear" style='margin-right: 5px'></i><?php echo $this->translate('599') ?>
                                                                            </a>
                                                                        </li>
                                                                    </div>-->
                                    </ul>
                                </li>
                                <li id="user_profile_link_divider" class="topbar-devider" style="visibility: hidden; display: none"></li>
                                <li class="hoverSelector" id="setting_link" style="visibility: hidden; display: none">
                                    <a style="cursor: pointer;"><?php echo $this->translate('601') ?></a>
                                    <i class="fa fa-building"></i>
                                    <ul id='topCompaniesBar' class="companies hoverSelectorBlock">
                                        <div class='col-md-12' id="topCompaniesBar_div"></div>
                                        <!--                            <div class='col-md-12'>
                                                                        <li style ='text-align: center;vertical-align: middle; line-height: 40px;'>
                                                                            <a href="">
                                                                                <i class="fa fa-plus"></i> <?php echo $this->translate('605') ?>
                                                                            </a>
                                                                        </li>
                                                                    </div>-->
                                        <div class='col-md-12' id='no_sub_company' style='visibility: hidden; display:none'>
                                            <li class="companies_top_text_header" style ='text-align: center;vertical-align: middle; line-height: 40px;'>
                                                <a href="">
                                                    <?php echo $this->translate('606') ?>  <i class="fa fa-exclamation"></i>
                                                </a>
                                            </li>
                                        </div>
                                    </ul>
                                </li>                        
                                <li id="setting_link_divider" class="topbar-devider" style="visibility: hidden; display: none"></li>
                                <li class="hoverSelector">
                                    <a><?php echo $this->translate('91') ?> </a>
                                    <i class="fa fa-globe"></i>
                                    <ul id='topLanguageBar' class="languages hoverSelectorBlock">                                    
                                    </ul>
                                </li>
                                <li class="topbar-devider"></li>   
                                <li><a href="<?php echo $this->url('sanalfabrika', array('action' => 'index', 'lang' => $this->langCode)); ?>"><?php echo $this->translate('89') ?></a></li>  
                                <li class="topbar-devider"></li>   
                                <li id="login_place" style="visibility: hidden; display: none">
                                    <a href="<?php echo $this->url('sanalfabrika', array('action' => 'login', 'lang' => $this->langCode)); ?>">
                                        <span>
                                            <?php echo $this->translate('30') ?>
                                        </span>
                                    </a>
                                </li>
                                <li id="logout_place" style="visibility: hidden; display: none">
                                    <a href="<?php echo $this->url('login', array('action' => 'logout', 'lang' => $this->langCode)); ?>">
                                        <span>
                                            <?php echo $this->translate('31') ?>
                                        </span>
                                    </a>
                                </li>
                                <!--<li><a href="<?php echo $this->url('login', array('action' => 'logout')); ?>"><span id="loging_ph"></span></a></li>-->   
                            </ul>
                        </div>
                        <!-- End Topbar -->

                        <!-- Toggle get grouped for better mobile display -->
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="fa fa-bars"></span>
                        </button>
                        <!-- End Toggle -->
                    </div><!--/end container-->

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse menu-xs navbar-responsive-collapse" >
                        <div class="container">
                            <ul class="nav navbar-nav " style="font-size: 10px;">
                                <li class="page-scroll home">
                                    <a href="<?php echo $this->url('sanalfabrika', array('action' => 'index'));
                                            ?>#body"><?php echo $this->translate('9') ?></a>
                                </li>
                                <li class="page-scroll">
                                    <a href="<?php echo $this->url('sanalfabrika', array('action' => 'index'));
                                            ?>#about"><?php echo $this->translate('229') ?></a>
                                </li>
                                <li class="dropdown">
                                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                                        <?php echo $this->translate('230') ?>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li class="page-scroll"><a href="<?php echo $this->url('sanalfabrika', array('action' => 'index'));
                                        ?>#ostimServices">
                                                <?php echo $this->translate('15') ?></a>
                                        </li>
                                    </ul>
                                </li>
                                <li class="page-scroll">
                                    <a href="<?php echo $this->url('sanalfabrika', array('action' => 'index'));
                                                ?>#news"><?php echo $this->translate('231') ?></a>
                                </li>
                                <li class="page-scroll">
                                    <a href="<?php echo $this->url('sanalfabrika', array('action' => 'index'));
                                                ?>#contact"><?php echo $this->translate('232') ?></a>
                                </li>
                                <!--                    <li class="dropdown">
                                                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                                <?php echo $this->translate('233') ?>
                                                        </a>
                                                        <ul class="dropdown-menu">
                                                            <li class="page-scroll">
                                                                <a href="<?php echo $this->url('sanalfabrika', array('action' => 'index'));
                                ?>#body"><?php echo $this->translate('9') ?></a>
                                                            </li>
                                                            <li class="page-scroll">
                                                                <a href="<?php echo $this->url('sanalfabrika', array('action' => 'index'));
                                ?>"><?php echo $this->translate('234') ?></a>
                                                            </li>
                                                        </ul>
                                                    </li>-->
                            </ul>
                        </div><!--/end container-->
                    </div><!--/navbar-collapse-->
                </div>
                <!--=== End Header ===-->
            </div>
        </div>
        <!--=== End Header ===-->

        <!--=== Breadcrumbs ===-->
        <div class="breadcrumbs">
            <!--<div style='background: #FAF8F0;' class="container">--> 
            <div style='background: #E0EDDF;' class="container">
                <h1 class="pull-left"><i class="fa fa-quote-left"></i><?php echo $this->translate('187') ?></h1>
                <ul class="pull-right breadcrumb">                        
                    <li>
                        <a href="<?php echo $this->url('sanalfabrika', array('action' => 'index'));
                                ?>">
                               <?php echo $this->translate('9') ?>
                        </a>
                    </li>
                    <li class="active"><?php echo $this->translate('187') ?></li>
                </ul>
            </div>
        </div><!--/breadcrumbs-->
        <!--=== End Breadcrumbs ===-->


        <!--=== Parallax Counter v4 ===-->
        <div class="parallax-counter-v4 parallaxBg">
            <div class="container content-xs">
                <div class="row">
                    <div class="col-md-3 col-xs-6 md-margin-bottom-50">
                        <i class="icon-cup"></i>
                        <span class="counter">265</span>
                        <h4><?php echo $this->translate("12") ?></h4>
                    </div>
                    <div class="col-md-3 col-xs-6 md-margin-bottom-50">
                        <i class="icon-clock"></i>
                        <span class="counter">5957</span>
                        <h4><?php echo $this->translate("507") ?></h4>
                    </div>
                    <div class="col-md-3 col-xs-6">
                        <i class="icon-emoticon-smile"></i>
                        <span class="counter">3495</span>
                        <h4><?php echo $this->translate("509") ?></h4>
                    </div>
                    <div class="col-md-3 col-xs-6">
                        <i class="icon-bulb"></i>
                        <span class="counter">576</span>
                        <h4><?php echo $this->translate("510") ?></h4>
                    </div>
                </div><!--/end row-->
            </div><!--/end container-->
        </div>
        <!--=== End Parallax Counter v4 ===-->

        <!--=== Content Part ===-->
        <div class="container content">
            <div class="row">
                <!-- Begin Sidebar Menu -->
                <div class="col-md-3 ">

                    <!-- Begin Task Progress -->
                    <div id="taskProgress">
                        <!--<div style='background: #EDE7DF;
                             border-radius: 5px;
                             padding: 10px;' class="panel-heading-v2 overflow-h">-->
                        <div style='background: #E0EDDF;
                             border-radius: 5px;
                             padding: 10px;' class="panel-heading-v2 overflow-h">
                            <h2 class="heading-xs pull-left">
                                <div class='headline'>
                                    <h4>
                                        <i class="fa fa-bar-chart-o"></i>
                                        <?php echo $this->translate('216') ?>
                                    </h4>
                                </div>
                            </h2>
                            <a href="javascript:;" onclick="event.preventDefault()"><i class="fa fa-cog pull-right"></i></a>
                        </div>                        
                        <h3 class="heading-xs">
                            <?php echo $this->translate('176') ?>
                            <span id="userGeneralInfoRegistrationProgress" 
                                  class="pull-right">0%</span>
                        </h3>
                        <div class="progress progress-u progress-xxs">
                            <div id='userGeneralInfoRegistrationProgressStyle' 
                                 style="width: 0%" aria-valuemax="100" aria-valuemin="0" 
                                 aria-valuenow="0" role="progressbar" 
                                 class="progress-bar progress-bar-u">
                            </div>
                        </div>
                        <h3 class="heading-xs">
                            <?php echo $this->translate('177') ?>
                            <span id="userAddressInfoRegistrationProgress" 
                                  class="pull-right">0%</span>
                        </h3>
                        <div class="progress progress-u progress-xxs">
                            <div id='userAddressInfoRegistrationProgressStyle' 
                                 style="width: 0%" aria-valuemax="100" aria-valuemin="0" 
                                 aria-valuenow="0" role="progressbar" 
                                 class="progress-bar progress-bar-blue">
                            </div>
                        </div>
                        <h3 class="heading-xs">
                            <?php echo $this->translate('178') ?>
                            <span id="userCommunicationInfoRegistrationProgress" 
                                  class="pull-right">0%</span>
                        </h3>
                        <div class="progress progress-u progress-xxs">
                            <div id='userCommunicationInfoRegistrationProgressStyle' 
                                 style="width: 0%" aria-valuemax="100" aria-valuemin="0" 
                                 aria-valuenow="0" role="progressbar" 
                                 class="progress-bar progress-bar-dark">
                            </div>
                        </div>                            
                        <h3 class="heading-xs">
                            <?php echo $this->translate('219') ?>
                            <span id="overallRegistrationProgress" class="pull-right">0%</span>
                        </h3>
                        <div class="progress progress-u progress-xxs margin-bottom-40">
                            <div id='overallRegistrationProgressStyle' style="width: 0%" 
                                 aria-valuemax="100" aria-valuemin="0" aria-valuenow="0" 
                                 role="progressbar" class="progress-bar progress-bar-dark">
                            </div>
                        </div>
                    </div>
                    <!-- End Task Progress -->
                    <hr>                       

                    <!--Notification-->
                    <!--                    <div class="profile">
                                            <div style='background: #E0EDDF;
                                                 border-radius: 5px;
                                                 padding: 10px;' class="panel-heading-v2 overflow-h"> 
                                            <div style='background: #E0EDDF;
                                                 border-radius: 5px;
                                                 padding: 10px;' class="panel-heading-v2 overflow-h">
                                                <h2 class="heading-xs pull-left">
                                                    <div class='headline'>
                                                        <h4>
                                                            <i class="fa fa-bell-o"></i>
                    <?php echo $this->translate('259') ?>
                                                        </h4>
                                                    </div>
                                                </h2>
                                                <a href="javascript:;" onclick="event.preventDefault()"><i class="fa fa-cog pull-right" style='color: #01DF01'></i></a>
                                            </div>
                                            <ul class="list-unstyled mCustomScrollbar margin-bottom-20" 
                                                data-mcs-theme="minimal-dark">
                                                <li class="notification">
                                                    <i class="icon-custom icon-sm rounded-x icon-bg-red icon-line icon-envelope"></i>
                                                    <div class="overflow-h">
                                                        <span><strong>Albert Heller</strong><?php echo $this->translate(' has sent you email.') ?> </span>
                                                        <small><?php echo $this->translate(' Two') ?><?php echo $this->translate(' minutes ago') ?></small>
                                                    </div>    
                                                </li>
                                                <li class="notification">
                                                    <img class="rounded-x" src="<?php echo $this->basePath('onyuz/standard/assets/img/testimonials/img6.jpg') ?>" alt="">
                                                    <div class="overflow-h">
                                                        <span><strong>Taylor Lee</strong><?php echo $this->translate(' started following you.') ?> </span>
                                                        <small><?php echo $this->translate(' Today') ?> 18:25 <?php echo $this->translate(' pm') ?></small>
                                                    </div>    
                                                </li>
                                                <li class="notification">
                                                    <i class="icon-custom icon-sm rounded-x icon-bg-yellow icon-line fa fa-bolt"></i>
                                                    <div class="overflow-h">
                                                        <span><strong>Natasha Kolnikova</strong><?php echo $this->translate(' accepted your invitation.') ?> </span>
                                                        <small><?php echo $this->translate(' Yesterday') ?> 1:07 <?php echo $this->translate(' pm') ?></small>
                                                    </div>    
                                                </li>
                                                <li class="notification">
                                                    <img class="rounded-x" src="<?php echo $this->basePath('onyuz/standard/assets/img/testimonials/img1.jpg') ?>" alt="">
                                                    <div class="overflow-h">
                                                        <span><strong>Mikel Andrews</strong><?php echo $this->translate(' commented on your Timeline.') ?> </span>
                                                        <small>23/12 11:01 <?php echo $this->translate(' am') ?></small>
                                                    </div>    
                                                </li>
                                                <li class="notification">
                                                    <i class="icon-custom icon-sm rounded-x icon-bg-blue icon-line fa fa-comments"></i>
                                                    <div class="overflow-h">
                                                        <span><strong>Bruno Js.</strong><?php echo $this->translate(' added you to group chating.') ?> </span>
                                                        <small><?php echo $this->translate(' Yesterday') ?> 1:07 <?php echo $this->translate(' pm') ?></small>
                                                    </div>    
                                                </li>
                                                <li class="notification">
                                                    <img class="rounded-x" src="<?php echo $this->basePath('onyuz/standard/assets/img/testimonials/img6.jpg') ?>" alt="">
                                                    <div class="overflow-h">
                                                        <span><strong>Taylor Lee</strong><?php echo $this->translate(' changed profile picture.') ?> </span>
                                                        <small>23/12 15:15 <?php echo $this->translate(' pm') ?></small>
                                                    </div>    
                                                </li>
                                            </ul>    
                                            <button type="button" class="btn-u btn-u-default btn-u-sm btn-block"><?php echo $this->translate('Load More') ?></button>
                                        </div>-->
                    <!--End Notification-->
                    <!--<hr>-->
                    <!-- Clients Block -->
                    <div id="clients">
                        <!--<div style='background: #DFE0ED;
                             border-radius: 5px;
                             padding: 10px;' class="panel-heading-v2 overflow-h">-->
                        <div style='background: #E0EDDF;
                             border-radius: 5px;
                             padding: 10px;' class="panel-heading-v2 overflow-h">
                            <h2 class="heading-xs pull-left">
                                <div class='headline'>
                                    <h4>
                                        <i class="fa fa-shopping-cart"></i>
                                        <?php echo $this->translate('107') ?>
                                    </h4>
                                </div>
                            </h2>
                            <a href="javascript:;" onclick="event.preventDefault()"><i class="fa fa-cog pull-right"></i></a>
                        </div>
                        <ul class="list-unstyled mCustomScrollbar margin-bottom-20" 
                            data-mcs-theme="minimal-dark">
                            <li class="clients-page">
                                <div class="row clients-page">
                                    <div>
                                        <img src="<?php echo $this->basePath('onyuz/standard/assets/img/clients2/emge-small.png') ?>" 
                                             class="img-responsive hover-effect center-block" 
                                             alt="" />
                                    </div>
                                    <div class="overflow-h col-md-12 headline">
                                        <h3>EMGE</h3>
                                        <ul class="list-unstyled">
                                            <li><i class="fa fa-map-marker color-green"></i><?php echo $this->translate('350') ?> </li>
                                            <li><i class="fa fa-globe color-green"></i> <a class="linked" href="#"> http://www.emge.com.tr/</a></li>
                                            <li><i class="fa fa-briefcase color-green"></i><?php echo $this->translate(' Aviation and Defense Cluster ') ?> </li>
                                        </ul>
                                        <p><?php echo $this->translate('1975 yılında DEMİR SANAYİ’ de 90m2’lik bir alanda “ERTUĞLAR” adı altında kurulmuş olan firmamız 
                                            1979 yılında OSTİM’ de 400m2’lik bir alanda üretimlerine devam etmiştir.') ?>
                                            <?php echo $this->translate('1981 yılında unvanını EMGE KOLLEKTİF ŞİRKETİ ELEKTRO MEKANİK GEREÇLER ENDÜSTRİSİ olarak değiştiren firmamız 1986 yılında 58. 
                                            sokak 16 numarada 800m2’lik kendi binasında üretimlerini sürdürmüş ve 2002 yılı Kasım ayında da 3000 m2’lik yeni binasına taşınmıştır.') ?> 
                                            <?php echo $this->translate('Ürün yelpazesini her geçen gün biraz daha genişleten firmamız, kalite ve müşteri memnuniyetini her zaman 
                                                ön planda tutmuş ve bu doğrultuda ISO 9001–2000 belgesini de almıştır. Yeni yerinde 7 adet atölye ile birçok sektörde üretimine devam etmektedir. ') ?>
                                            <?php echo $this->translate('Kurulduğu günden bugüne kadar her geçen gün alt yapısını güçlendirerek ve değişen teknolojiyi takip ederek, müşteri beklentilerinin önünde üretim yapmayı ve en iyi hizmeti süreklilik anlayışı içerisinde sunmayı benimsemiştir. 
                                            Seçkin kadrosuyla ülke ekonomisine katkıda bulunmaya çalışan firmamızın faaliyetleri arasında talaşlı imalat, plastik enjeksiyon ve kesme kalıpları, plastik enjeksiyon baskı işleri, ultrasonik kaynak işleri, 
                                            analog ve dijital ölçü aletleri, akım trafoları, born klemens üretimi, buksel soket üretimi, orta gerilim emniyet teçhizatları üretimi, hortum kesme makineleri, akortlu montaj bantları ve özel sistem makine üretimleri yer almaktadır.') ?>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <!-- End Clients Block-->


                </div>
                <!-- End Sidebar Menu -->

                <!-- Begin Content -->
                <div class="col-md-9">
                    <!-- Tabs -->
                    <div class="tab-v1">
                        <ul id="primaryTabs" class="nav nav-tabs">                                
                            <!-- To disable tabs first it is needed to change tab class to disabled
                            then remove href attribute value due to deactivate tab transition on click event..-->
                            <li id="userGeneralInfoTab" class="active">
                                <a href="#userGeneralInfo" data-toggle="tab">
                                    <?php echo $this->translate('176') ?>
                                </a>
                            </li>
                            <li id="userAddressInfoTab"   onclick="checkUGI()">
                                <a href="#userAddressInfo" data-toggle="tab">
                                    <?php echo $this->translate('177') ?>
                                </a>
                            </li>
                            <li id="userCommunicationInfoTab" class="disabled" onclick="checkUAI()">
                                <a href="#userCommunicationInfo" data-toggle="tab">
                                    <?php echo $this->translate('178') ?>
                                </a>
                            </li>
                            <li id="companyInfoTab" class="disabled" onclick="checkCI()">
                                <a href="#companyInfo" data-toggle="tab">
                                    <?php echo $this->translate('179') ?>
                                </a>
                            </li>
                        </ul> 
                        <div id="tabsContentsSection" class="tab-content box">
                            <!-- User General Info  -->
                            <div class="tab-pane fade in active" id="userGeneralInfo">
                                <form id="userGeneralInfoForm" class="sky-form">
                                    <header>
                                        <div class='headline'>
                                            <h2><?php echo $this->translate('176') ?></h2>
                                        </div>
                                    </header>
                                    <fieldset>
                                        <div class="row">
                                            <section>
                                                <label class="label"><?php echo $this->translate('188') ?></label>
                                                <div class="input-group">
                                                    <div class="input-group-addon">
                                                        <i class="fa fa-users"></i>
                                                    </div>
                                                    <input type="text" name="userFirstName" 
                                                           id="userFirstName" required="true"
                                                           class="form-control validate[required,custom[onlyLetterSp]]"
                                                           onchange="taskProgressPerTabs()">
                                                </div>
                                            </section>
                                            <section>
                                                <label class="label"><?php echo $this->translate('189') ?></label>
                                                <div class="input-group">
                                                    <div class="input-group-addon">
                                                        <i class="fa fa-users"></i>
                                                    </div>
                                                    <input type="text" name="userLastName" 
                                                           id="userLastName" required="true"
                                                           class="form-control validate[required,custom[onlyLetterSp]]"
                                                           onchange="taskProgressPerTabs()">
                                                </div>
                                            </section>
                                            <section>
                                                <label class="label"><?php echo $this->translate('112') ?></label>
                                                <div class="input-group">
                                                    <div class="input-group-addon">
                                                        <i class="fa fa-envelope"></i>
                                                    </div>
                                                    <input class="form-control validate[required,custom[email]]" 
                                                           type="email" name="useremail" id="useremail" 
                                                           onchange="taskProgressPerTabs();
                                                                   checkUserName()">
                                                </div>
                                            </section>
                                            <section>
                                                <label class="label"><?php echo $this->translate('190') ?></label>
                                                <div class="input-group">
                                                    <div class="input-group-addon">
                                                        <i class="fa fa-barcode"></i>
                                                    </div>
                                                    <input disabled='disabled' type="text" name="preferedUsername" 
                                                           id="preferedUsername" required="true"
                                                           class="form-control validate[required,custom[sfUserName]] disabled "
                                                           onchange="taskProgressPerTabs()">
                                                </div>
                                            </section>                                            
<!--                                            <section>
                                                <label class="label"><?php echo $this->translate('191') ?></label>
                                                <div class="input-group">
                                                    <div class="input-group-addon">
                                                        <i class="fa fa-lock"></i>
                                                    </div>
                                                    <input type="password" name="userPreferedPassword" 
                                                           id="userPreferedPassword" required="true"
                                                           class="form-control validate[required,minSize[8],maxSize[20]]"
                                                           onchange="taskProgressPerTabs()">
                                                </div>
                                            </section>
                                            <section>
                                                <label class="label"><?php echo $this->translate('192') ?></label>
                                                <div class="input-group">
                                                    <div class="input-group-addon">
                                                        <i class="fa fa-key"></i>
                                                    </div>
                                                    <input type="password" name="repeatedUserPreferedPassword" 
                                                           id="repeatedUserPreferedPassword" required="true"
                                                           class="form-control validate[required,equals[userPreferedPassword]] text-input">
                                                </div>
                                            </section>                                                -->
<!--                                            <section> 
                                                <label class="checkbox">
                                                    <input type="checkbox" name="showPassword" 
                                                           id="showPassword">
                                                    <i></i><?php echo $this->translate('222') ?> 
                                                </label>
                                            </section>-->
                                            <section>
                                                <label class="label"><?php echo $this->translate('194') ?></label>
                                                <div id="userPreferedLanguage" />                                                     
                                                <i></i>
                                            </section>                                                  
                                        </div>
                                        <div class="row"> 
                                            <label class="checkbox">
                                                <input required="true" type="checkbox" checked="true" name="makePublicProfile" 
                                                       id="makePublicProfile" onchange="changePublicProfile()">
                                                <i></i><?php echo $this->translate('195') ?>
                                            </label> 
                                        </div>
                                        <footer>
                                            <div id="userButtons">
                                                <button type="submit" id="userGeneralInfoFormSubmit" 
                                                        class="btn-u btn-u-dark-blue" onclick="submitUserGeneralInfoForm()">                                                                
                                                </button>
                                                <button type="button" id="userGeneralInfoFormReset" 
                                                        class="btn-u" onclick="resetForm()">
                                                            <?php echo $this->translate('186') ?>
                                                </button>
                                            </div>
                                        </footer>
                                    </fieldset>
                                </form>         
                            </div>
                            <!--// End User General Info  -->
                            <!-- User Address Info  -->
                            <div class="tab-pane fade box" id="userAddressInfo" >
                                <form id="userAddressInfoForm" class="sky-form">
                                    <header>
                                        <div class='headline'>
                                            <?php echo $this->translate('177') ?>
                                        </div>
                                    </header>
                                    <fieldset>
                                        <div class="row">
                                            <section>
                                                <button type="button" class="btn-u btn-green col-md-12" 
                                                        id="showAllAddresses_btn" 
                                                        data-toggle="modal" 
                                                        data-target="#addressModal"
                                                        onclick="find_registered_addresses()">
                                                            <?php echo $this->translate('208') ?>
                                                </button> 
                                            </section>                                               
                                        </div>
                                        <hr>
                                        <div class="row">
                                            <section>
                                                <label class="label"><?php echo $this->translate('213') ?></label>
                                                <div id="addressTypesCombo" />
                                            </section>
                                        </div>
                                        <div class="row">
                                            <section>
                                                <label class="label"><?php echo $this->translate('135') ?></label>
                                                <div id="usercountry" />
                                            </section>
                                            <section>
                                                <div id='cityNameSection'>
                                                    <label class="label"><?php echo $this->translate('138') ?></label>
                                                    <div class="input-group">
                                                        <div class="input-group-addon">
                                                            <i class="fa fa-home"></i>
                                                        </div>
                                                        <input type="text" name="userCityName" 
                                                               id="userCityName"
                                                               class="form-control validate[required,onlyLetterSp]"
                                                               onchange="taskProgressPerTabs()">
                                                    </div> 
                                                </div>
                                            </section>
                                            <section>
                                                <div id='cityDropdownSection'>
                                                    <label class="label"><?php echo $this->translate('138') ?></label>
                                                    <div id="usercity" >  </div> 
                                                </div>
                                            </section>
                                            <section>
                                                <div id='districtDropdownSection'>
                                                    <label class="label"><?php echo $this->translate('139') ?></label>
                                                    <div id="userdistrict" ></div> 
                                                </div>
                                            </section>
                                            <section>
                                                <label class="label"><?php echo $this->translate('220') ?></label>
                                                <div class="input-group">
                                                    <div class="input-group-addon">
                                                        <i class="fa fa-home"></i>
                                                    </div>
                                                    <input type="text" name="userAddress1" 
                                                           id="userAddress1"
                                                           class="form-control validate[sfAddress]">
                                                </div> 
                                            </section>
                                            <section>
                                                <label class="label"><?php echo $this->translate('221') ?></label>
                                                <div class="input-group">
                                                    <div class="input-group-addon">
                                                        <i class="fa fa-home"></i>
                                                    </div>
                                                    <input type="text" name="userAddress2" 
                                                           id="userAddress2"
                                                           class="form-control validate[sfAddress]"
                                                           onchange="taskProgressPerTabs()">
                                                </div> 
                                            </section>                                                 
                                            <section>
                                                <label class="label"><?php echo $this->translate('145') ?></label>
                                                <div class="input-group">
                                                    <div class="input-group-addon">
                                                        <i class="fa fa-home"></i>
                                                    </div>
                                                    <input type="text" name="userPostalCode" id="userPostalCode"
                                                           class="form-control validate[custom[onlyLetterNumber]"
                                                           onchange="taskProgressPerTabs()">
                                                </div>
                                            </section>                                                                                                
                                            <section>
                                                <label class="label"><?php echo $this->translate('201') ?></label>
                                                <label class="textarea">
                                                    <i class="icon-prepend fa fa-comment"></i>
                                                    <textarea rows="4" name="addressDescription" id="addressDescription"></textarea>
                                                </label>
                                            </section>
                                        </div>
                                        <footer>
                                            <label class="checkbox">
                                                <input required="true" type="checkbox" checked="true" name="makePublicAddress" 
                                                       id="makePublicAddress" onchange="changePublicAddress()">
                                                <i></i><?php echo $this->translate('223') ?>
                                            </label> 
                                        </footer>
                                        <footer>
                                            <div id="userButtons">
                                                <button type="submit" id="userAddressInfoFormSubmit" 
                                                        class="btn-u btn-u-dark-blue" 
                                                        onclick="submitUserAddressInfoForm()">                                                                
                                                </button>
                                                <button type="button" id="userAddressInfoFormReset" 
                                                        class="btn-u" 
                                                        onclick="resetForm()">
                                                            <?php echo $this->translate('186') ?>
                                                </button>
                                            </div>
                                        </footer>
                                    </fieldset>
                                </form>
                            </div>
                            <!--// End User Address Info  -->
                            <!-- User Communication Info  -->
                            <div class="tab-pane fade" id="userCommunicationInfo">
                                <form id="userCommunicationInfoForm" class="sky-form">
                                    <header>
                                        <div class='headline'>
                                            <?php echo $this->translate('178') ?>
                                        </div>
                                    </header>
                                    <fieldset>
                                        <div class='row'>                                                
                                            <section>
                                                <button type="button" class="btn-u btn-green col-md-12" 
                                                        id="showAllContacts_btn" 
                                                        data-toggle="modal" 
                                                        data-target="#contactsModal"
                                                        onclick="find_registered_contacts()">
                                                            <?php echo $this->translate('225') ?>
                                                </button> 
                                            </section> 
                                        </div> 
                                        <hr>                                           
                                        <div class="row">
                                            <section>
                                                <label class="label"><?php echo $this->translate('196') ?></label>
                                                <div id='communicationTypes'>                                                        
                                                </div>
                                            </section> 
                                            <section>
                                                <label class="checkbox">
                                                    <input required="true" type="checkbox" checked="true" name="makePublicCommunication" 
                                                           id="makePublicCommunication" onchange="changePublicCommunication()">
                                                    <i></i><?php echo $this->translate('224') ?>
                                                </label> 
                                            </section>
                                            <section>
                                                <label class="label"><?php echo $this->translate('201') ?></label>
                                                <label class="textarea">
                                                    <i class="icon-prepend fa fa-comment"></i>
                                                    <textarea rows="4" name="contactDescription" id="contactDescription"></textarea>
                                                </label>
                                            </section>
                                            <section>
                                                <label class="checkbox">
                                                    <input type="checkbox" name="defaultContactNumber" id="defaultContactNumber">
                                                    <i></i><?php echo $this->translate('198') ?> 
                                                </label>
                                            </section>       
                                            <section>                                                                
                                                <label class="label"><?php echo $this->translate('199') ?></label>                                                                
                                                <div class="input-group">                                                                    
                                                    <input type="phone" class="form-control validation[custom[onlyNumberSp]]" 
                                                           name="contactNumber" id="contactNumber" onchange="taskProgressPerTabs()">                                                                    
                                                    <span class="input-group-btn">
                                                        <button class="btn btn-u" type="button" id="submitContactNumber" onclick="submitUserContactNumber()"><?php echo $this->translate('200') ?></button>
                                                    </span>
                                                </div>
                                            </section>
                                        </div>
                                    </fieldset>
                                    <fieldset>
                                        <div class="row"> 
                                            <label class="checkbox">
                                                <input required="true" type="checkbox" 
                                                       name="terms" id="terms" onchange="activateButtons(), taskProgressPerTabs()">
                                                <i></i><?php echo $this->translate('203') ?>
                                            </label> 
                                        </div>
                                    </fieldset>
                                    <fieldset>
                                        <div class="row">
                                            <div id="userButtons">
                                                <button type="button" id="userCommunicationInfoFormFinalize" 
                                                        class="btn-u btn-u-dark-blue disabled"  
                                                        onclick="completeUserSubmissionProcess()">
                                                            <?php echo $this->translate('204') ?>
                                                </button>
                                                <button type="submit" id="userCommunicationInfoFormSubmit" 
                                                        class="btn-u btn-u-default disabled"  
                                                        onclick="submitUserInfoForm()">
                                                </button>
                                                <button type="button" id="userCommunicationInfoFormReset" 
                                                        class="btn-u" onclick="resetForm()">
                                                            <?php echo $this->translate('186') ?>
                                                </button>
                                            </div>
                                        </div>
                                    </fieldset> 
                                </form>   
                            </div>
                            <!--// End User Communication Info  -->
                            <!-- Company Info Form -->
                            <div class="tab-pane fade" id="companyInfo">
                                <form id="companyInfoForm" class="sky-form">
                                    <header>
                                        <div class='headline'>
                                            <?php echo $this->translate('179') ?>
                                        </div>
                                    </header>
                                    <fieldset>
                                        <div class="row">
                                            <section>
                                                <label class="label"><?php echo $this->translate('206') ?></label>
                                                <label class="input">
                                                    <i class="icon-prepend fa fa-empire"></i>
                                                    <input required='true' type="text" style="padding-left: 50px"
                                                           class="form-control validate[minSize[6],maxSize[150]]" 
                                                           name="companyName" id="companyName">
                                                </label>
                                            </section>
                                            <section>
                                                <label class="label"><?php echo $this->translate('227') ?></label>
                                                <label class="input">
                                                    <i class="icon-prepend fa fa-empire"></i>
                                                    <input required='true' type="text" style="padding-left: 50px"
                                                           class="form-control validate[required,minSize[2],maxSize[30]]" 
                                                           name="companyShortName" id="companyShortName">
                                                </label>
                                            </section>
                                            <section>
                                                <label class="label"><?php echo $this->translate("511") ?></label>
                                                <div id="companyCountry" />
                                            </section>                                            
                                            <section>
                                                <label class="label"><?php echo $this->translate('126') ?></label>
                                                <label class="input">
                                                    <i class="icon-prepend fa fa-money"></i>
                                                    <input type="text" name="companyTaxNumber" id="companyTaxNumber">
                                                </label>
                                            </section>
                                            <section>
                                                <label class="label"><?php echo $this->translate('127') ?></label>
                                                <label class="input">
                                                    <i class="icon-prepend fa fa-money"></i>
                                                    <input type="text" name="companyTaxOffice" id="companyTaxOffice">
                                                </label>
                                            </section>
                                            <section>
                                                <label class="label"><?php echo $this->translate('128') ?></label>
                                                <label class="input">
                                                    <i class="icon-prepend fa fa-plus-square"></i>
                                                    <input type="text" name="companySocialSecurityNumber" id="companySocialSecurityNumber">
                                                </label>
                                            </section>
                                            <section>
                                                <label class="label"><?php echo $this->translate('235') ?></label>
                                                <div id='companyOwnershipStatus'>                                                        
                                                </div>
                                            </section> 
                                            <section>
                                                <label class="label"><?php echo $this->translate('226') ?></label>
                                                <label class="input">
                                                    <i class="icon-prepend fa fa-barcode"></i>
                                                    <input type="DUNS" class="form-control validation[custom[onlyNumberSp]]" 
                                                           name="companyDUNSNumber" id="companyDUNSNumber">
                                                </label>
                                            </section>
                                            <section>
                                                <label class="label"><?php echo $this->translate('129') ?></label> 
                                                <label class="input">
                                                    <i class="icon-prepend fa fa-calendar"></i>
                                                    <input class="form-control validate[required,custom[date]]" 
                                                           style="padding-left: 50px" onchange="milliseconds()"
                                                           type="text" name="companyFoundationDate" id="companyFoundationDate">
                                                </label>
                                            </section>
                                            <section>
                                                <label class="label"><?php echo $this->translate('130') ?></label> 
                                                <label class="input">
                                                    <i class="icon-prepend fa fa-globe"></i>
                                                    <input class="form-control validate[custom[url]]"
                                                           style="padding-left: 50px"
                                                           type="url" name="companyWebAddress" id="companyWebAddress"
                                                           placeholder="http:// or https://">
                                                </label>
                                                <div class="note">Please Note: URL begin with http:// or https://</div>

                                            </section>
                                            <section>
                                                <label class="label"><?php echo $this->translate('201') ?></label>
                                                <label class="textarea">
                                                    <i class="icon-prepend fa fa-comment"></i>
                                                    <textarea rows="4" name="companyDescription" id="companyDescription"></textarea>
                                                </label>
                                            </section>
                                            <section>
                                                <label class="checkbox">
                                                    <input required="true" type="checkbox" checked="true" name="makePublicCompany" 
                                                           id="makePublicCompany" onchange="makePublicCompany()">
                                                    <i></i><?php echo $this->translate('512') ?>
                                                </label> 
                                            </section>   
                                        </div>                                     
                                        <footer>
                                            <button id='companyInfoSubmissionBtn' type="submit" class="btn-u btn-u-default" onclick="companyInfoSubmission()"><?php echo $this->translate('131') ?></button>
                                            <button id='companyInfoCancelBtn' type="button" class="btn-u" onclick="window.history.back();"><?php echo $this->translate('228') ?></button>
                                        </footer>
                                    </fieldset>
                                </form>
                            </div>
                            <!-- End Company Info Forms -->
                        </div>
                    </div>
                    <!-- End Tabs-->
                </div>
                <!-- End Content -->
            </div>          
        </div><!--/container-->     
        <!--=== End Content Part ===-->


        <!--=== Footer Version 1 ===-->
        <div class="footer-v1">
            <div class="footer">
                <div class="container">
                    <div class="row">
                        <!-- About -->
                        <div class="col-md-3 md-margin-bottom-40">
                            <a href="index.phtml"><img id="logo-footer" class="footer-logo" 
                                                       src="<?php echo $this->basePath('onyuz/standard/assets/img/logo2-default.png') ?>" 
                                                       alt=""></a>
                            <p><?php echo $this->translate('264') ?></p>
                        </div><!--/col-md-3-->
                        <!-- End About -->

                        <!-- Latest -->
                        <div class="col-md-3 md-margin-bottom-40">
                            <div class="posts">
                                <div class="headline"><h2><?php echo $this->translate('261') ?></h2></div>
                                <ul class="list-unstyled latest-list">
                                    <li>
                                        <a href="#"><?php echo $this->translate('265') ?></a>
                                        <small><?php echo $this->translate('286') ?> 8, 2016</small>
                                    </li>
                                    <li>
                                        <a href="#"><?php echo $this->translate('266') ?></a>
                                        <small><?php echo $this->translate('285') ?> 23, 2016</small>
                                    </li>
                                    <li>
                                        <a href="#"><?php echo $this->translate('267') ?></a>
                                        <small><?php echo $this->translate('296') ?> 15, 2016</small>
                                    </li>
                                </ul>
                            </div>
                        </div><!--/col-md-3-->  
                        <!-- End Latest --> 

                        <!-- Link List -->
                        <div class="col-md-3 md-margin-bottom-40">
                            <div class="headline"><h2><?php echo $this->translate('262') ?></h2></div>
                            <ul class="list-unstyled link-list">
                                <li><a href="http://www.ostim.org.tr/"><?php echo $this->translate('268') ?></a><i class="fa fa-angle-right"></i></li>
                                <li><a href="http://www.sanayi.gov.tr/"><?php echo $this->translate('269') ?></a><i class="fa fa-angle-right"></i></li>
                                <li><a href="https://www.tubitak.gov.tr/"><?php echo $this->translate('270') ?></a><i class="fa fa-angle-right"></i></li>
                                <li><a href="http://www.kosgeb.gov.tr/"><?php echo $this->translate('271') ?></a><i class="fa fa-angle-right"></i></li>
                                <!--<li><a href="#"><?php echo $this->translate('') ?></a><i class="fa fa-angle-right"></i></li>-->
                            </ul>
                        </div><!--/col-md-3-->
                        <!-- End Link List -->                    

                        <!-- Address -->
                        <div class="col-md-3 map-img md-margin-bottom-40">
                            <div class="headline"><h2><?php echo $this->translate('110') ?></h2></div>                         
                            <address class="md-margin-bottom-40">
                                100. Yıl Bulvarı No: 101/A <br />
                                OSTIM, Ankara <br />
                                Turkey <br />
                                <?php echo $this->translate('147') ?> :  +90 312 385 50 90 <br />
                                <?php echo $this->translate('148') ?>:    +90 312 354 58 98 <br />
                                <?php echo $this->translate('112') ?>: <a href="mailto:info@ostim.com.tr" class="">info@ostim.com.tr</a>
                            </address>
                        </div><!--/col-md-3-->
                        <!-- End Address -->
                    </div>
                </div> 
            </div><!--/footer-->

            <div class="copyright">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">                     
                            <p>
                                2016 &copy; <?php echo $this->translate('274') ?>
                                <a href="#"><?php echo $this->translate('273') ?></a> | <a href="#"><?php echo $this->translate('272') ?></a>
                            </p>
                        </div>

                        <!-- Social Links -->
                        <div class="col-md-6">
                            <ul class="footer-socials list-inline">
                                <li>
                                    <a href="https://www.facebook.com/OstimOSB/" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Facebook">
                                        <i class="fa fa-facebook"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Skype">
                                        <i class="fa fa-skype"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="https://plus.google.com/+OST%C4%B0MOSB1967" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Google Plus">
                                        <i class="fa fa-google-plus"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="https://www.linkedin.com/in/ostim-osb-2b94b847" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Linkedin">
                                        <i class="fa fa-linkedin"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="https://www.instagram.com/ostimosb/" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Instagram">
                                        <i class="fa fa-instagram"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="https://twitter.com/ostimosb" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Twitter">
                                        <i class="fa fa-twitter"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Dribbble">
                                        <i class="fa fa-dribbble"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <!-- End Social Links -->
                    </div>
                </div> 
            </div><!--/copyright-->
        </div>    
        <!--=== End Footer Version 1 ===-->
    </div><!--/End Wrapepr-->

    <!--********************************************************************-->
    <!--//********************* Modals Section******************************-->
    <!--********************************************************************-->


    <!-- Registered Address Modal -->        
    <div class="modal fade bs-example-modal-lg" id="addressModal" tabindex="-1" 
         role="dialog" aria-labelledby="addressModalLabel" 
         aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button aria-hidden="true" data-dismiss="modal" class="close" type="button">x</button>
                    <h4 id="addressModalLabel1" class="modal-title"><?php echo $this->translate('209') ?></h4>
                </div>
                <!--Hover Rows-->
                <div>
                    <div class="panel panel-grey margin-bottom-40">
                        <div class="panel-heading">
                            <h3 class="panel-title"><i class="fa fa-phone"></i><?php echo $this->translate('513') ?></h3>
                        </div>
                        <div class="panel-body">
                            <table id="table_address_modal">
                                <thead>
                                    <tr>
<!--                                        <th data-field="state" data-checkbox="true"></th>
                                        <th><?php echo $this->translate('213') ?></th>
                                        <th><?php echo $this->translate('135') ?></th>
                                        <th><?php echo $this->translate('138') ?></th>
                                        <th><?php echo $this->translate('139') ?></th>
                                        <th><?php echo $this->translate('220') ?></th>
                                        <th><?php echo $this->translate('221') ?></th>
                                        <th><?php echo $this->translate('145') ?></th>
                                        <th><?php echo $this->translate('201') ?></th> -->
                                    </tr>
                                </thead>
                            </table>
                        </div>                  
                    </div>
                    <!--End Striped and Hover Rows-->
                    <div class="modal-footer">
                        <button data-dismiss="modal" class="btn-u btn-u-default" type="button"><?php echo $this->translate('212') ?></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--// End of test of Registered Address Modal-->


    <!-- Registered Contacts Modal -->        
    <div class="modal fade bs-example-modal-lg" id="contactsModal" tabindex="-1" 
         role="dialog" aria-labelledby="contactModalLabel" 
         aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button aria-hidden="true" data-dismiss="modal" class="close" type="button">x</button>
                    <h4 id="contactModalLabel1" class="modal-title"><?php echo $this->translate('514') ?></h4>
                </div>
                <!--Hover Rows-->
                <div>
                    <div class="panel panel-grey margin-bottom-40">
                        <div class="panel-heading">
                            <h3 class="panel-title"><i class="fa fa-phone"></i><?php echo $this->translate('210') ?></h3>
                        </div>
                        <div class="panel-body">
                            <table id="table_contacts_modal">
                                <thead>
                                    <tr>
<!--                                        <th data-field="state" data-checkbox="true"></th>
                                        <th ><?php echo $this->translate('515') ?></th>
                                        <th ><?php echo $this->translate('199') ?></th>
                                        <th ><?php echo $this->translate('516') ?></th>-->
                                    </tr>
                                </thead>
                            </table>
                        </div>                  
                    </div>
                    <!--End Striped and Hover Rows-->
                    <div class="modal-footer">
                        <button data-dismiss="modal" class="btn-u btn-u-default" type="button"><?php echo $this->translate('212') ?></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--// End of test of Registered Contacts Modal-->

    <!--********************************************************************-->
    <!--//********************* End of Modals Section******************************-->
    <!--********************************************************************-->

</body>
</html>