<input id="requestUriRegulated" type="hidden"  value="<?php echo $this->requestUriRegulated; ?>"></input>
<input id="langCode" type="hidden"  value="<?php echo $this->langCode; ?>"></input>


<body

    <!--=== Style Switcher ===-->    
    <i class="style-switcher-btn fa fa-cogs hidden-xs"></i>
    <div class="style-switcher animated fadeInRight">
        <div class="style-swticher-header">
            <div class="style-switcher-heading">Style Switcher</div>            
            <div class="theme-close"><i class="icon-close"></i></div>
        </div>

        <div class="style-swticher-body">
            <!-- Theme Colors -->
            <div class="style-switcher-heading">Theme Colors</div>
            <ul class="list-unstyled">
                <li class="theme-default theme-active" data-style="default" data-header="light"></li>
                <li class="theme-blue" data-style="blue" data-header="light"></li>
                <li class="theme-orange" data-style="orange" data-header="light"></li>
                <li class="theme-red" data-style="red" data-header="light"></li>
                <li class="theme-light" data-style="light" data-header="light"></li>
                <li class="theme-purple last" data-style="purple" data-header="light"></li>
                <li class="theme-aqua" data-style="aqua" data-header="light"></li>
                <li class="theme-brown" data-style="brown" data-header="light"></li>
                <li class="theme-dark-blue" data-style="dark-blue" data-header="light"></li>
                <li class="theme-light-green" data-style="light-green" data-header="light"></li>
                <li class="theme-dark-red" data-style="dark-red" data-header="light"></li>
                <li class="theme-teal last" data-style="teal" data-header="light"></li>
            </ul>

            <!-- Theme Skins -->
            <div class="style-switcher-heading">Theme Skins</div>
            <div class="row no-col-space margin-bottom-20 skins-section">
                <div class="col-xs-6">
                    <button data-skins="default" class="btn-u btn-u-xs btn-u-dark btn-block active-switcher-btn handle-skins-btn">Light</button>
                </div>
                <div class="col-xs-6">
                    <button data-skins="dark" class="btn-u btn-u-xs btn-u-dark btn-block skins-btn">Dark</button>
                </div>
            </div>            

            <hr>

            <!-- Layout Styles -->
            <div class="style-switcher-heading">Layout Styles</div>
            <div class="row no-col-space margin-bottom-20">
                <div class="col-xs-6">
                    <a href="javascript:void(0);" class="btn-u btn-u-xs btn-u-dark btn-block active-switcher-btn wide-layout-btn">Wide</a>                
                </div>
                <div class="col-xs-6">
                    <a href="javascript:void(0);" class="btn-u btn-u-xs btn-u-dark btn-block boxed-layout-btn">Boxed</a>                
                </div>
            </div>            

            <hr>

            <!-- Theme Type -->
            <div class="style-switcher-heading">Theme Types and Versions</div>
            <div class="row no-col-space margin-bottom-10">
                <div class="col-xs-6">
                    <a href="Shop-UI/index.html" class="btn-u btn-u-xs btn-u-dark btn-block">Shop UI <small class="dp-block">Template</small></a>
                </div>
                <div class="col-xs-6">
                    <a href="One-Page/index.html" class="btn-u btn-u-xs btn-u-dark btn-block">One Page <small class="dp-block">Template</small></a>
                </div>
            </div>           

            <div class="row no-col-space">
                <div class="col-xs-6">
                    <a href="Blog/index.html" class="btn-u btn-u-xs btn-u-dark btn-block">Blog <small class="dp-block">Template</small></a>
                </div>
                <div class="col-xs-6">
                    <a href="RTL/index.html" class="btn-u btn-u-xs btn-u-dark btn-block">RTL <small class="dp-block">Version</small></a>
                </div>
            </div>           
        </div>
    </div><!--/style-switcher-->
    <!--=== End Style Switcher ===-->    

    <div class="wrapper">
        <!--=== Header ===-->    
        <div class="header">
            <div class="container">
                <!-- Logo -->
                <a class="logo" href="index-2.html">
                    <img src="<?php echo $this->basePath('onyuz/standard/assets/img/logo1-default.png') ?>" alt="Logo">
                </a>
                <!-- End Logo -->

                <!-- Topbar -->
                <div class="topbar">
                    <ul class="loginbar pull-right">
                        <li class="hoverSelector">
                            <i class="fa fa-globe"></i>
                            <a><?php echo $this->translate('Languages') ?></a>
                            <ul class="languages hoverSelectorBlock">
                                <li class="active">
                                    <a href="#">English <i class="fa fa-check"></i></a> 
                                </li>
                                <li><a href="#">Turkish</a></li>
                                <li><a href="#">Russian</a></li>
                                <li><a href="#">German</a></li>
                            </ul>
                        </li>
                        <li class="topbar-devider"></li>   
                        <li><a href="page_faq.html">Help</a></li>  
                        <li class="topbar-devider"></li>   
                        <li><a href="page_login.html">Login</a></li>   
                    </ul>
                </div>
                <!-- End Topbar -->

                <!-- Toggle get grouped for better mobile display -->
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="fa fa-bars"></span>
                </button>
                <!-- End Toggle -->
            </div><!--/end container-->

            
            <!--=== End Header ===-->

            <!--=== Breadcrumbs ===-->
            <div class="breadcrumbs">
                <div class="container">
                    <h1 class="pull-left"><?php echo $this->translate('Registration') ?></h1>
                    <ul class="pull-right breadcrumb">
                        <li><a href="https://www.dev.sanalfabrika.com/ostim/sanalfabrika"><?php echo $this->translate('Home') ?></a></li>
                        <li class="active"><?php echo $this->translate('Registration') ?></li>
                    </ul>
                </div>
            </div><!--/breadcrumbs-->
            <!--=== End Breadcrumbs ===-->

            <!--=== Content Part ===-->
            <div class="container content">
                <div class="row">
                    <!-- Begin Sidebar Menu -->
                    
                    <!-- End Sidebar Menu -->

                    <!-- Begin Content -->
                    <div class="col-md-15">
                        <!-- Tabs -->
                        <div class="tab-v1">
                            <ul class="nav nav-tabs">
                                <li class="active"><a href="#userInfo" data-toggle="tab"><?php echo $this->translate('User Information') ?></a></li>
                                <li><a href="#companyInfo" data-toggle="tab"><?php echo $this->translate('Company Information') ?></a></li>
                            </ul>                
                            <div class="tab-content">
                                <!-- Datepicker Forms -->
                                <div class="tab-pane fade in active" id="userInfo">
                                    <form action="#" id="userInfoForm" class="sky-form">
                                        <header><?php echo $this->translate('User Information') ?></header>

                                        <fieldset>
                                            <div class="row">
                                                <section class="col col-6">
                                                    <label class="label"><?php echo $this->translate('Name') ?></label>
                                                    <label class="input">
                                                        <i class="icon-append fa fa-asterisk"></i>
                                                        <input type="text" name="required">
                                                    </label>
                                                </section>
                                                <section class="col col-6">
                                                    <label class="label"><?php echo $this->translate('Surname') ?></label>
                                                    <label class="input">
                                                        <i class="icon-append fa fa-asterisk"></i>
                                                        <input type="text" name="required">
                                                    </label>
                                                </section>
                                            </div>
                                            <div class="row">
                                                <section class="col col-6">
                                                    <label class="label"><?php echo $this->translate('Proposed Username') ?></label>
                                                    <label class="input">
                                                        <i class="icon-append fa fa-asterisk"></i>
                                                        <input type="text" name="required">
                                                    </label>
                                                </section>
                                                <section class="col col-6">
                                                    <label class="label"><?php echo $this->translate('Email') ?></label>
                                                    <label class="input">
                                                        <i class="icon-append fa fa-asterisk"></i>
                                                        <input type="email" name="required">
                                                    </label>
                                                </section>
                                            </div>
                                            
                                            
                                            
                                            
                                            <section>
                                                <label class="label">Select single date</label> 
                                                <label class="input">
                                                    <i class="icon-append fa fa-calendar"></i>
                                                    <input type="text" name="date" id="date">
                                                </label>
                                            </section>

                                            <label class="label">Select date range</label>  
                                            <div class="row">   
                                                <section class="col col-6">
                                                    <label class="input">
                                                        <i class="icon-append fa fa-calendar"></i>
                                                        <input type="text" name="start" id="start" placeholder="Start date">
                                                    </label>
                                                </section>
                                                <section class="col col-6">
                                                    <label class="input">
                                                        <i class="icon-append fa fa-calendar"></i>
                                                        <input type="text" name="finish" id="finish" placeholder="Expected finish date">
                                                    </label>
                                                </section>
                                            </div>                  
                                        </fieldset>

                                        <fieldset>
                                            <section>
                                                <label class="label">Select single date with inline datepicker</label>
                                                <div id="inline"></div>
                                            </section>

                                            <label class="label">Select date range with inline datepickers</label>  
                                            <div class="row">   
                                                <section class="col col-6">
                                                    <div id="inline-start"></div>
                                                </section>
                                                <section class="col col-6">
                                                    <div id="inline-finish"></div>
                                                </section>
                                            </div>                  
                                        </fieldset>
                                    </form>         
                                </div>
                                <!-- End Datepicker Forms -->

                                <!-- Validation Forms -->
                                <div class="tab-pane fade" id="companyInfo">
                                    <form action="#" id="companyInfoForm" class="sky-form">
                                        <header><?php echo $this->translate('Company Information') ?></header>

                                        <fieldset>
                                            <div class="row">
                                                <section class="col col-6">
                                                    <label class="label">Required field</label>
                                                    <label class="input">
                                                        <i class="icon-append fa fa-asterisk"></i>
                                                        <input type="text" name="required">
                                                    </label>
                                                </section>
                                                <section class="col col-6">
                                                    <label class="label">Email validation</label>
                                                    <label class="input">
                                                        <i class="icon-append fa fa-envelope"></i>
                                                        <input type="email" name="email">
                                                    </label>
                                                </section>
                                            </div>

                                            <div class="row">
                                                <section class="col col-6">
                                                    <label class="label">URL validation</label>
                                                    <label class="input">
                                                        <i class="icon-append fa fa-globe"></i>
                                                        <input type="url" name="url">
                                                    </label>
                                                </section>
                                                <section class="col col-6">
                                                    <label class="label">Date validation</label>
                                                    <label class="input">
                                                        <i class="icon-append fa fa-calendar"></i>
                                                        <input type="text" name="date">
                                                    </label>
                                                </section>
                                            </div>

                                            <div class="row">
                                                <section class="col col-4">
                                                    <label class="label">Minimum length</label>
                                                    <label class="input">
                                                        <i class="icon-append fa fa-asterisk"></i>
                                                        <input type="text" name="min">
                                                    </label>
                                                </section>
                                                <section class="col col-4">
                                                    <label class="label">Maximum length</label>
                                                    <label class="input">
                                                        <i class="icon-append fa fa-asterisk"></i>
                                                        <input type="text" name="max">
                                                    </label>
                                                </section>
                                                <section class="col col-4">
                                                    <label class="label">Range length</label>
                                                    <label class="input">
                                                        <i class="icon-append fa fa-asterisk"></i>
                                                        <input type="text" name="range">
                                                    </label>
                                                </section>
                                            </div>
                                        </fieldset>

                                        <fieldset>
                                            <div class="row">
                                                <section class="col col-6">
                                                    <label class="label">Digits validation</label>
                                                    <label class="input">
                                                        <i class="icon-append fa fa-asterisk"></i>
                                                        <input type="text" name="digits">
                                                    </label>
                                                </section>
                                                <section class="col col-6">
                                                    <label class="label">Decimal number validation</label>
                                                    <label class="input">
                                                        <i class="icon-append fa fa-asterisk"></i>
                                                        <input type="text" name="number">
                                                    </label>
                                                </section>
                                            </div>

                                            <div class="row">
                                                <section class="col col-4">
                                                    <label class="label">Minimum value</label>
                                                    <label class="input">
                                                        <i class="icon-append fa fa-asterisk"></i>
                                                        <input type="text" name="minVal">
                                                    </label>
                                                </section>
                                                <section class="col col-4">
                                                    <label class="label">Maximum value</label>
                                                    <label class="input">
                                                        <i class="icon-append fa fa-asterisk"></i>
                                                        <input type="text" name="maxVal">
                                                    </label>
                                                </section>
                                                <section class="col col-4">
                                                    <label class="label">Range value</label>
                                                    <label class="input">
                                                        <i class="icon-append fa fa-asterisk"></i>
                                                        <input type="text" name="rangeVal">
                                                    </label>
                                                </section>
                                            </div>
                                        </fieldset>

                                        <footer>
                                            <button type="submit" class="btn-u btn-u-default"><?php echo $this->translate('Submit') ?></button>
                                            <button type="button" class="btn-u" onclick="window.history.back();"><?php echo $this->translate('Cancel') ?></button>
                                        </footer>
                                    </form>
                                </div>
                                <!-- End Validation Forms -->

                                <!-- Masking Forms -->
                                <div class="tab-pane fade" id="messages-1">
                                    <form action="#" id="sky-form2" class="sky-form">
                                        <header>Available masking rules</header>

                                        <fieldset>
                                            <section>
                                                <label class="label">Date masking</label>
                                                <label class="input">
                                                    <i class="icon-append fa fa-calendar"></i>
                                                    <input type="text" name="date" id="date1">
                                                </label>
                                            </section>

                                            <section>
                                                <label class="label">Phone masking</label>
                                                <label class="input">
                                                    <i class="icon-append fa fa-phone"></i>
                                                    <input type="tel" name="phone" id="phone">
                                                </label>
                                            </section>

                                            <section>
                                                <label class="label">Credit card masking</label>
                                                <label class="input">
                                                    <i class="icon-append fa fa-credit-card"></i>
                                                    <input type="text" name="card" id="card">
                                                </label>
                                            </section>

                                            <section>
                                                <label class="label">Serial number masking</label>
                                                <label class="input">
                                                    <i class="icon-append fa fa-asterisk"></i>
                                                    <input type="text" name="serial" id="serial">
                                                </label>
                                            </section>

                                            <section>
                                                <label class="label">Tax ID masking</label>
                                                <label class="input">
                                                    <i class="icon-append fa fa-briefcase"></i>
                                                    <input type="text" name="tax" id="tax">
                                                </label>
                                            </section>
                                        </fieldset>

                                        <footer>
                                            <button type="submit" class="btn-u btn-u-default">Submit</button>
                                            <button type="button" class="btn-u" onclick="window.history.back();">Back</button>
                                        </footer>
                                    </form>
                                </div>
                                <!-- End Masking Forms -->
                            </div>
                        </div>
                        <!-- End Tabs-->
                    </div>
                    <!-- End Content -->
                </div>          
            </div><!--/container-->     
            <!--=== End Content Part ===-->

            <!--=== Footer Version 1 ===-->
            <div class="footer-v1">
                <div class="footer">
                    <div class="container">
                        <div class="row">
                            <!-- About -->
                            <div class="col-md-3 md-margin-bottom-40">
                                <a href="index-2.html"><img id="logo-footer" class="footer-logo" src="<?php echo $this->basePath('onyuz/standard/assets/img/logo2-default.png') ?>" alt=""></a>
                                <p>About Unify dolor sit amet, consectetur adipiscing elit. Maecenas eget nisl id libero tincidunt sodales.</p>
                                <p>Duis eleifend fermentum ante ut aliquam. Cras mi risus, dignissim sed adipiscing ut, placerat non arcu.</p>    
                            </div><!--/col-md-3-->
                            <!-- End About -->

                            <!-- Latest -->
                            <div class="col-md-3 md-margin-bottom-40">
                                <div class="posts">
                                    <div class="headline"><h2>Latest Posts</h2></div>
                                    <ul class="list-unstyled latest-list">
                                        <li>
                                            <a href="#">Incredible content</a>
                                            <small>May 8, 2014</small>
                                        </li>
                                        <li>
                                            <a href="#">Best shoots</a>
                                            <small>June 23, 2014</small>
                                        </li>
                                        <li>
                                            <a href="#">New Terms and Conditions</a>
                                            <small>September 15, 2014</small>
                                        </li>
                                    </ul>
                                </div>
                            </div><!--/col-md-3-->  
                            <!-- End Latest --> 

                            <!-- Link List -->
                            <div class="col-md-3 md-margin-bottom-40">
                                <div class="headline"><h2>Useful Links</h2></div>
                                <ul class="list-unstyled link-list">
                                    <li><a href="#">About us</a><i class="fa fa-angle-right"></i></li>
                                    <li><a href="#">Portfolio</a><i class="fa fa-angle-right"></i></li>
                                    <li><a href="#">Latest jobs</a><i class="fa fa-angle-right"></i></li>
                                    <li><a href="#">Community</a><i class="fa fa-angle-right"></i></li>
                                    <li><a href="#">Contact us</a><i class="fa fa-angle-right"></i></li>
                                </ul>
                            </div><!--/col-md-3-->
                            <!-- End Link List -->                    

                            <!-- Address -->
                            <div class="col-md-3 map-img md-margin-bottom-40">
                                <div class="headline"><h2>Contact Us</h2></div>                         
                                <address class="md-margin-bottom-40">
                                    25, Lorem Lis Street, Orange <br />
                                    California, US <br />
                                    Phone: 800 123 3456 <br />
                                    Fax: 800 123 3456 <br />
                                    Email: <a href="mailto:info@anybiz.com" class="">info@anybiz.com</a>
                                </address>
                            </div><!--/col-md-3-->
                            <!-- End Address -->
                        </div>
                    </div> 
                </div><!--/footer-->

                <div class="copyright">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-6">                     
                                <p>
                                    2015 &copy; All Rights Reserved.
                                    <a href="#">Privacy Policy</a> | <a href="#">Terms of Service</a>
                                </p>
                            </div>

                            <!-- Social Links -->
                            <div class="col-md-6">
                                <ul class="footer-socials list-inline">
                                    <li>
                                        <a href="#" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Facebook">
                                            <i class="fa fa-facebook"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Skype">
                                            <i class="fa fa-skype"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Google Plus">
                                            <i class="fa fa-google-plus"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Linkedin">
                                            <i class="fa fa-linkedin"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Pinterest">
                                            <i class="fa fa-pinterest"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Twitter">
                                            <i class="fa fa-twitter"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Dribbble">
                                            <i class="fa fa-dribbble"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <!-- End Social Links -->
                        </div>
                    </div> 
                </div><!--/copyright-->
            </div>     
            <!--=== End Footer Version 1 ===-->
        </div><!--/End Wrapepr-->

</body>

<!-- Mirrored from htmlstream.com/preview/unify-v1.8/shortcode_form_advanced.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 09 Dec 2015 13:36:16 GMT -->
</html>